In [1]:
%cd '/home/mojtaba.kananisarche/'

/home/mojtaba.kananisarche

In [2]:
from Zh.src.utils.csvwriter import CSVWriter
from Zh.src.utils.video import get_video_info

In [3]:
video_path = '/work/long_lab/Mojtaba/data/UTA/1.4-augmentated_masked/brightness_alpha0.8_beta-10/1_01_0_30fps_brightness_alpha0.8_beta-10.mp4'
csv_path = '/work/long_lab/Mojtaba/data/UTA/1.4.2-augmentated_masked_embedded/brightness_alpha0.8_beta-10/1_01_0_30fps_brightness_alpha0.8_beta-10.csv'

In [5]:
c = CSVWriter(csv_path)
v = get_video_info(file_path = video_path)

In [8]:
c.get_current_line_number()

18072

In [3]:
csv_path_2 = '/home/mojtaba.kananisarche/Zh/temp/5_52_0_30fps_blendshape.csv'
c = CSVWriter(csv_path_2)

In [4]:
c.clear()

In [6]:
c.write('1')

In [ ]:
from transformers import ViTImageProcessor, TFViTModel
import tensorflow as tf

/home/mojtaba.kananisarche/.conda/envs/.cvenv/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2025-05-28 21:21:32.904520: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1748488895.079532 2001220 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1748488896.038780 2001220 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1748489030.589189 2001220 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1748489030.592421 2001220 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1748489030.592437 2001220 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1748489030.592450 2001220 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2025-05-28 21:23:53.338361: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [4]:
model_path = '/work/long_lab/Mojtaba/src/process/vit-base-patch16-224-in21k'

processor = ViTImageProcessor.from_pretrained(model_path)
model = TFViTModel.from_pretrained(model_path)

2025-05-28 21:26:31.271783: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)
All PyTorch model weights were used when initializing TFViTModel.

All the weights of TFViTModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFViTModel for predictions without further training.

In [5]:
from Zh.src.utils.face_detector import FaceDetector
from Zh.src.utils.video import *
input_video_path = '/home/mojtaba.kananisarche/Zh/data/UTA/1.2.1-raw_30fps_cropped/1_04_0_30fps_sq_cropped.mp4'
vr = VideoReader(input_video_path)
frame = vr._read_frame_at_index(15)[1]

In [7]:
inputs = processor(images=frame, return_tensors="np")
outputs = model(**inputs)
last_hidden_states = outputs.last_hidden_state

In [16]:
list(np.round(last_hidden_states[0,1].numpy(),3))

[np.float32(-0.377),
 np.float32(0.265),
 np.float32(-0.031),
 np.float32(-0.234),
 np.float32(0.358),
 np.float32(-0.424),
 np.float32(-0.254),
 np.float32(0.109),
 np.float32(0.097),
 np.float32(-0.088),
 np.float32(0.144),
 np.float32(-0.401),
 np.float32(-0.043),
 np.float32(0.141),
 np.float32(-0.3),
 np.float32(0.078),
 np.float32(0.101),
 np.float32(0.122),
 np.float32(-0.293),
 np.float32(0.24),
 np.float32(-0.323),
 np.float32(-0.075),
 np.float32(-0.213),
 np.float32(0.029),
 np.float32(0.146),
 np.float32(-0.187),
 np.float32(-0.228),
 np.float32(-0.138),
 np.float32(-0.147),
 np.float32(-0.008),
 np.float32(0.024),
 np.float32(0.049),
 np.float32(-0.176),
 np.float32(0.158),
 np.float32(-0.166),
 np.float32(-0.185),
 np.float32(-0.007),
 np.float32(0.089),
 np.float32(0.033),
 np.float32(-0.179),
 np.float32(0.09),
 np.float32(0.183),
 np.float32(-0.128),
 np.float32(-0.064),
 np.float32(-0.441),
 np.float32(-0.234),
 np.float32(-0.337),
 np.float32(-0.122),
 np.float32(0.022),
 np.float32(0.104),
 np.float32(-0.144),
 np.float32(-0.04),
 np.float32(-0.052),
 np.float32(0.037),
 np.float32(0.349),
 np.float32(-0.186),
 np.float32(0.238),
 np.float32(-0.138),
 np.float32(0.113),
 np.float32(0.069),
 np.float32(0.062),
 np.float32(0.068),
 np.float32(-0.361),
 np.float32(0.038),
 np.float32(-0.075),
 np.float32(-0.096),
 np.float32(-0.282),
 np.float32(0.029),
 np.float32(0.174),
 np.float32(0.141),
 np.float32(-0.001),
 np.float32(-0.028),
 np.float32(-0.054),
 np.float32(-0.168),
 np.float32(-0.341),
 np.float32(0.116),
 np.float32(-0.084),
 np.float32(-0.038),
 np.float32(-0.162),
 np.float32(-0.424),
 np.float32(-0.113),
 np.float32(-0.109),
 np.float32(0.275),
 np.float32(-0.259),
 np.float32(-0.09),
 np.float32(-0.116),
 np.float32(0.187),
 np.float32(0.086),
 np.float32(-0.445),
 np.float32(0.044),
 np.float32(0.24),
 np.float32(-0.096),
 np.float32(-0.145),
 np.float32(-0.709),
 np.float32(-0.115),
 np.float32(-0.212),
 np.float32(0.065),
 np.float32(-0.029),
 np.float32(0.237),
 np.float32(-0.006),
 np.float32(-0.104),
 np.float32(-0.145),
 np.float32(-0.213),
 np.float32(0.338),
 np.float32(0.128),
 np.float32(0.094),
 np.float32(0.082),
 np.float32(-0.024),
 np.float32(-0.132),
 np.float32(-0.127),
 np.float32(-0.058),
 np.float32(-0.11),
 np.float32(-0.4),
 np.float32(0.012),
 np.float32(0.298),
 np.float32(0.218),
 np.float32(0.059),
 np.float32(0.203),
 np.float32(-0.17),
 np.float32(-0.038),
 np.float32(0.111),
 np.float32(-0.023),
 np.float32(0.1),
 np.float32(-0.051),
 np.float32(0.184),
 np.float32(0.042),
 np.float32(0.155),
 np.float32(-0.203),
 np.float32(-0.049),
 np.float32(-0.057),
 np.float32(0.003),
 np.float32(-0.294),
 np.float32(-0.235),
 np.float32(0.113),
 np.float32(0.018),
 np.float32(0.159),
 np.float32(-0.053),
 np.float32(0.067),
 np.float32(-0.15),
 np.float32(-0.134),
 np.float32(0.178),
 np.float32(-0.373),
 np.float32(-0.039),
 np.float32(0.254),
 np.float32(-0.008),
 np.float32(0.002),
 np.float32(0.21),
 np.float32(0.264),
 np.float32(0.009),
 np.float32(0.224),
 np.float32(0.066),
 np.float32(-0.244),
 np.float32(0.062),
 np.float32(-0.223),
 np.float32(0.138),
 np.float32(-0.26),
 np.float32(-0.173),
 np.float32(-0.092),
 np.float32(0.361),
 np.float32(-0.07),
 np.float32(0.05),
 np.float32(-0.243),
 np.float32(-0.276),
 np.float32(0.453),
 np.float32(0.17),
 np.float32(0.286),
 np.float32(0.06),
 np.float32(0.016),
 np.float32(0.168),
 np.float32(0.066),
 np.float32(-0.249),
 np.float32(-0.37),
 np.float32(-0.131),
 np.float32(-0.203),
 np.float32(-0.307),
 np.float32(0.312),
 np.float32(0.254),
 np.float32(0.187),
 np.float32(0.146),
 np.float32(-0.195),
 np.float32(-0.203),
 np.float32(0.011),
 np.float32(0.193),
 np.float32(-0.018),
 np.float32(0.031),
 np.float32(0.094),
 np.float32(-0.261),
 np.float32(0.464),
 np.float32(0.307),
 np.float32(0.103),
 np.float32(-0.297),
 np.float32(0.217),
 np.float32(0.032),
 np.float32(0.018),
 np.float32(0.099),
 np.float32(0.155),
 np.float32(0.086),
 np.float32(-0.024),
 np.float32(0.308),
 np.float32(0.177),
 np.float32(-0.122),
 np.float32(-0.017),
 np.float32(-0.002),
 np.float32(-0.404),
 np.float32(-0.491),
 np.float32(-0.259),
 np.float32(0.179),
 np.float32(-0.186),
 np.float32(0.021),
 np.float32(0.383),
 np.float32(-0.273),
 np.float32(0.043),
 np.float32(-0.22),
 np.float32(0.035),
 np.float32(-0.118),
 np.float32(0.151),
 np.float32(0.369),
 np.float32(0.352),
 np.float32(0.325),
 np.float32(-0.484),
 np.float32(-0.09),
 np.float32(0.099),
 np.float32(-0.263),
 np.float32(-0.04),
 np.float32(0.069),
 np.float32(-0.268),
 np.float32(-0.431),
 np.float32(0.283),
 np.float32(-0.392),
 np.float32(-0.16),
 np.float32(0.034),
 np.float32(-0.462),
 np.float32(-0.321),
 np.float32(0.08),
 np.float32(0.013),
 np.float32(-0.089),
 np.float32(0.257),
 np.float32(-0.125),
 np.float32(0.006),
 np.float32(0.417),
 np.float32(0.077),
 np.float32(0.4),
 np.float32(0.153),
 np.float32(0.187),
 np.float32(0.126),
 np.float32(-0.137),
 np.float32(0.15),
 np.float32(-0.128),
 np.float32(-0.106),
 np.float32(-0.11),
 np.float32(-0.08),
 np.float32(0.165),
 np.float32(0.029),
 np.float32(0.006),
 np.float32(0.242),
 np.float32(-0.177),
 np.float32(-0.076),
 np.float32(0.305),
 np.float32(0.021),
 np.float32(-0.177),
 np.float32(-0.154),
 np.float32(0.089),
 np.float32(0.114),
 np.float32(0.011),
 np.float32(0.32),
 np.float32(0.195),
 np.float32(0.204),
 np.float32(0.116),
 np.float32(-0.142),
 np.float32(0.099),
 np.float32(0.009),
 np.float32(-0.087),
 np.float32(0.271),
 np.float32(-0.338),
 np.float32(-0.103),
 np.float32(0.132),
 np.float32(-0.154),
 np.float32(0.326),
 np.float32(-0.0),
 np.float32(-0.018),
 np.float32(-0.436),
 np.float32(-0.216),
 np.float32(0.285),
 np.float32(0.095),
 np.float32(-0.133),
 np.float32(0.02),
 np.float32(-0.319),
 np.float32(-0.136),
 np.float32(-0.101),
 np.float32(0.025),
 np.float32(0.151),
 np.float32(0.02),
 np.float32(-0.265),
 np.float32(-0.174),
 np.float32(-0.03),
 np.float32(-0.092),
 np.float32(0.018),
 np.float32(0.12),
 np.float32(-0.123),
 np.float32(-0.145),
 np.float32(-0.079),
 np.float32(0.236),
 np.float32(0.171),
 np.float32(-0.179),
 np.float32(-0.338),
 np.float32(0.015),
 np.float32(0.037),
 np.float32(0.052),
 np.float32(-0.029),
 np.float32(0.274),
 np.float32(-0.107),
 np.float32(0.101),
 np.float32(0.029),
 np.float32(-0.128),
 np.float32(-0.125),
 np.float32(0.132),
 np.float32(-0.151),
 np.float32(-0.082),
 np.float32(-0.045),
 np.float32(0.239),
 np.float32(0.083),
 np.float32(0.254),
 np.float32(-0.143),
 np.float32(-0.157),
 np.float32(-0.069),
 np.float32(-0.229),
 np.float32(-0.083),
 np.float32(0.018),
 np.float32(0.027),
 np.float32(-0.322),
 np.float32(-0.138),
 np.float32(0.007),
 np.float32(0.177),
 np.float32(-0.154),
 np.float32(-0.113),
 np.float32(-0.013),
 np.float32(-0.248),
 np.float32(0.182),
 np.float32(0.012),
 np.float32(0.319),
 np.float32(0.209),
 np.float32(-0.257),
 np.float32(0.066),
 np.float32(0.377),
 np.float32(-0.035),
 np.float32(0.194),
 np.float32(-0.402),
 np.float32(0.117),
 np.float32(0.019),
 np.float32(-0.347),
 np.float32(-0.014),
 np.float32(0.075),
 np.float32(0.146),
 np.float32(-0.236),
 np.float32(0.37),
 np.float32(-0.063),
 np.float32(0.018),
 np.float32(-0.282),
 np.float32(-0.053),
 np.float32(-0.177),
 np.float32(0.189),
 np.float32(0.247),
 np.float32(-0.142),
 np.float32(-0.062),
 np.float32(-0.373),
 np.float32(0.302),
 np.float32(-0.418),
 np.float32(-0.055),
 np.float32(-0.033),
 np.float32(-0.074),
 np.float32(-0.171),
 np.float32(-0.26),
 np.float32(-0.213),
 np.float32(0.272),
 np.float32(0.05),
 np.float32(-0.011),
 np.float32(0.131),
 np.float32(0.002),
 np.float32(-0.079),
 np.float32(0.119),
 np.float32(0.131),
 np.float32(0.049),
 np.float32(-0.141),
 np.float32(-0.148),
 np.float32(0.335),
 np.float32(0.088),
 np.float32(-0.263),
 np.float32(-0.119),
 np.float32(-0.09),
 np.float32(0.295),
 np.float32(-0.045),
 np.float32(-0.441),
 np.float32(-0.136),
 np.float32(-0.165),
 np.float32(0.123),
 np.float32(0.011),
 np.float32(0.092),
 np.float32(0.177),
 np.float32(-0.103),
 np.float32(0.32),
 np.float32(-0.163),
 np.float32(-0.267),
 np.float32(-0.224),
 np.float32(-0.056),
 np.float32(0.182),
 np.float32(-0.121),
 np.float32(0.189),
 np.float32(0.04),
 np.float32(0.148),
 np.float32(-0.023),
 np.float32(0.088),
 np.float32(-0.228),
 np.float32(-0.025),
 np.float32(0.249),
 np.float32(-0.174),
 np.float32(-0.22),
 np.float32(0.007),
 np.float32(-0.235),
 np.float32(-0.459),
 np.float32(-0.161),
 np.float32(0.3),
 np.float32(-0.339),
 np.float32(0.049),
 np.float32(-0.022),
 np.float32(-0.131),
 np.float32(0.048),
 np.float32(0.218),
 np.float32(0.043),
 np.float32(-0.033),
 np.float32(-0.138),
 np.float32(0.085),
 np.float32(-0.151),
 np.float32(0.043),
 np.float32(-0.21),
 np.float32(-0.204),
 np.float32(-0.334),
 np.float32(-0.441),
 np.float32(-0.115),
 np.float32(0.262),
 np.float32(0.194),
 np.float32(-0.217),
 np.float32(-0.072),
 np.float32(0.265),
 np.float32(-0.122),
 np.float32(-0.262),
 np.float32(-0.19),
 np.float32(-0.177),
 np.float32(-0.164),
 np.float32(-0.183),
 np.float32(-0.172),
 np.float32(-0.125),
 np.float32(0.1),
 np.float32(0.334),
 np.float32(-0.274),
 np.float32(0.093),
 np.float32(-0.4),
 np.float32(0.108),
 np.float32(0.157),
 np.float32(0.155),
 np.float32(0.098),
 np.float32(-0.305),
 np.float32(0.096),
 np.float32(-0.005),
 np.float32(0.038),
 np.float32(0.252),
 np.float32(-0.017),
 np.float32(0.302),
 np.float32(0.083),
 np.float32(0.198),
 np.float32(0.316),
 np.float32(-0.129),
 np.float32(0.01),
 np.float32(-0.28),
 np.float32(-0.077),
 np.float32(0.104),
 np.float32(-0.035),
 np.float32(-0.293),
 np.float32(0.031),
 np.float32(-0.012),
 np.float32(-0.321),
 np.float32(-0.18),
 np.float32(-0.065),
 np.float32(0.238),
 np.float32(-0.031),
 np.float32(0.072),
 np.float32(0.155),
 np.float32(0.161),
 np.float32(-0.05),
 np.float32(0.269),
 np.float32(-0.119),
 np.float32(0.016),
 np.float32(0.123),
 np.float32(0.22),
 np.float32(-0.248),
 np.float32(-0.069),
 np.float32(-0.22),
 np.float32(0.344),
 np.float32(-0.116),
 np.float32(-0.048),
 np.float32(-0.041),
 np.float32(-0.16),
 np.float32(-0.092),
 np.float32(0.151),
 np.float32(-0.092),
 np.float32(0.019),
 np.float32(-0.161),
 np.float32(0.15),
 np.float32(-0.142),
 np.float32(0.027),
 np.float32(-0.021),
 np.float32(-0.066),
 np.float32(-0.121),
 np.float32(0.359),
 np.float32(0.201),
 np.float32(0.171),
 np.float32(-0.253),
 np.float32(-0.109),
 np.float32(0.124),
 np.float32(0.09),
 np.float32(-0.118),
 np.float32(-0.013),
 np.float32(0.336),
 np.float32(-0.287),
 np.float32(-0.034),
 np.float32(-0.072),
 np.float32(0.305),
 np.float32(0.116),
 np.float32(-0.287),
 np.float32(-0.301),
 np.float32(0.101),
 np.float32(-0.214),
 np.float32(-0.046),
 np.float32(0.139),
 np.float32(-0.105),
 np.float32(-0.039),
 np.float32(-0.003),
 np.float32(0.13),
 np.float32(-0.293),
 np.float32(-0.231),
 np.float32(0.213),
 np.float32(-0.09),
 np.float32(-0.309),
 np.float32(0.108),
 np.float32(0.136),
 np.float32(-0.048),
 np.float32(0.157),
 np.float32(-0.453),
 np.float32(0.06),
 np.float32(-0.19),
 np.float32(-0.09),
 np.float32(-0.284),
 np.float32(-0.148),
 np.float32(0.109),
 np.float32(0.176),
 np.float32(0.174),
 np.float32(0.446),
 np.float32(0.166),
 np.float32(-0.004),
 np.float32(0.085),
 np.float32(0.11),
 np.float32(-0.029),
 np.float32(0.029),
 np.float32(-0.177),
 np.float32(0.032),
 np.float32(-0.102),
 np.float32(-0.201),
 np.float32(0.466),
 np.float32(-0.053),
 np.float32(0.144),
 np.float32(-0.022),
 np.float32(-0.128),
 np.float32(-0.346),
 np.float32(0.058),
 np.float32(0.247),
 np.float32(-0.228),
 np.float32(-0.035),
 np.float32(0.065),
 np.float32(-0.214),
 np.float32(0.084),
 np.float32(-0.281),
 np.float32(-0.079),
 np.float32(-0.089),
 np.float32(-0.235),
 np.float32(0.462),
 np.float32(0.068),
 np.float32(0.315),
 np.float32(-0.258),
 np.float32(-0.12),
 np.float32(0.05),
 np.float32(-0.373),
 np.float32(-0.076),
 np.float32(-0.08),
 np.float32(-0.112),
 np.float32(0.011),
 np.float32(-0.121),
 np.float32(0.43),
 np.float32(-0.396),
 np.float32(-0.259),
 np.float32(0.11),
 np.float32(0.094),
 np.float32(0.019),
 np.float32(0.213),
 np.float32(-0.121),
 np.float32(-0.004),
 np.float32(0.13),
 np.float32(-0.062),
 np.float32(0.094),
 np.float32(-0.296),
 np.float32(0.126),
 np.float32(0.148),
 np.float32(0.196),
 np.float32(0.14),
 np.float32(0.054),
 np.float32(-0.36),
 np.float32(-0.468),
 np.float32(-0.013),
 np.float32(-0.119),
 np.float32(-0.253),
 np.float32(-0.056),
 np.float32(-0.031),
 np.float32(-0.004),
 np.float32(0.127),
 np.float32(0.105),
 np.float32(-0.005),
 np.float32(-0.001),
 np.float32(-0.203),
 np.float32(-0.059),
 np.float32(-0.008),
 np.float32(0.22),
 np.float32(-0.01),
 np.float32(-0.15),
 np.float32(0.11),
 np.float32(0.053),
 np.float32(0.314),
 np.float32(0.32),
 np.float32(-0.161),
 np.float32(-0.158),
 np.float32(0.043),
 np.float32(-0.041),
 np.float32(0.507),
 np.float32(-0.19),
 np.float32(-0.174),
 np.float32(0.028),
 np.float32(-0.131),
 np.float32(-0.068),
 np.float32(-0.033),
 np.float32(-0.106),
 np.float32(0.123),
 np.float32(0.36),
 np.float32(-0.014),
 np.float32(-0.089),
 np.float32(0.051),
 np.float32(0.015),
 np.float32(-0.412),
 np.float32(-0.386),
 np.float32(0.285),
 np.float32(-0.378),
 np.float32(-0.219),
 np.float32(-0.003),
 np.float32(-0.286),
 np.float32(-0.088),
 np.float32(0.161),
 np.float32(0.145),
 np.float32(0.132),
 np.float32(0.279),
 np.float32(-0.056),
 np.float32(-0.082),
 np.float32(-0.076),
 np.float32(0.052),
 np.float32(-0.415),
 np.float32(0.099),
 np.float32(0.044),
 np.float32(0.117),
 np.float32(0.074),
 np.float32(-0.112),
 np.float32(0.174),
 np.float32(0.214),
 np.float32(-0.17),
 np.float32(-0.14),
 np.float32(0.32),
 np.float32(0.283),
 np.float32(-0.049),
 np.float32(0.128),
 np.float32(-0.052),
 np.float32(0.117),
 np.float32(-0.082),
 np.float32(-0.06),
 np.float32(0.024),
 np.float32(0.105),
 np.float32(-0.074),
 np.float32(-0.311),
 np.float32(0.231),
 np.float32(0.029),
 np.float32(0.191),
 np.float32(0.07),
 np.float32(0.131),
 np.float32(0.273),
 np.float32(-0.106),
 np.float32(0.026),
 np.float32(0.349),
 np.float32(0.314),
 np.float32(0.115),
 np.float32(0.111),
 np.float32(-0.465),
 np.float32(0.114),
 np.float32(-0.388),
 np.float32(-0.316),
 np.float32(-0.165),
 np.float32(0.12),
 np.float32(0.05),
 np.float32(-0.66),
 np.float32(-0.41),
 np.float32(0.176),
 np.float32(0.258),
 np.float32(-0.175),
 np.float32(-0.381),
 np.float32(0.013),
 np.float32(0.353),
 np.float32(0.094),
 np.float32(-0.098),
 np.float32(-0.451),
 np.float32(0.127),
 np.float32(-0.236),
 np.float32(-0.483),
 np.float32(0.194),
 np.float32(-0.12),
 np.float32(-0.14),
 np.float32(0.249),
 np.float32(0.276),
 np.float32(-0.32),
 np.float32(-0.039),
 np.float32(0.136),
 np.float32(-0.202),
 np.float32(-0.416),
 np.float32(-0.207),
 np.float32(0.034),
 np.float32(0.274),
 np.float32(0.005),
 np.float32(-0.565),
 np.float32(-0.302),
 np.float32(0.222),
 np.float32(0.102),
 np.float32(0.119),
 np.float32(0.206),
 np.float32(-0.131),
 np.float32(0.283),
 np.float32(-0.039),
 np.float32(-0.005),
 np.float32(0.078),
 np.float32(-0.228),
 np.float32(0.45),
 np.float32(-0.276),
 np.float32(-0.138),
 np.float32(0.079),
 np.float32(-0.088),
 np.float32(0.12),
 np.float32(0.175),
 np.float32(-0.064),
 np.float32(-0.22),
 np.float32(0.176),
 np.float32(-0.181),
 np.float32(0.059),
 np.float32(-0.143),
 np.float32(-0.156),
 np.float32(-0.029),
 np.float32(-0.249),
 np.float32(0.332),
 np.float32(-0.291)]

In [1]:
%cd '/home/mojtaba.kananisarche/'

from Zh.src.process.face_video_processor import *

input_folder = "/home/mojtaba.kananisarche/Zh/data/UTA/1-raw_30fps"
# output_folder='/work/long_lab/Mojtaba/data/UTA/1.3.1-augmentated_embedded'
output_folder='/home/mojtaba.kananisarche/Zh/temp/out2'
# output_folder = "/home/mojtaba.kananisarche/Zh/temp/out"

vp = VideoProcessor(
    input_folder=input_folder, output_folder=output_folder, use_tqdm=False
)
augmentations = {
    "gaussianblur": [{"kernel_size": 3}, {"kernel_size": 5}],
    "brightness": [{"alpha": 1.2, "beta": 10}, {"alpha": 0.8, "beta": -10}],
    "contrast": [{"alpha": 1.5, "beta": 0}, {"alpha": 0.7, "beta": 0}],
    "flip": [
        {"flip_code": 1},  # Vertical flip
    ],
    "grayscale": [{}],  # No parameters needed
    "rotate": [{"angle": 5}, {"angle": -5}],
}
vp.process_multiple_videos(
    # video_files=[],  # all
    video_files = ['1_06_5_30fps.mp4'],
    # video_files=os.listdir(input_folder)[:2],
    parallel=True,
    start_second=0,
    # end_second=None,
    end_second=2,
    augmentations=augmentations,
    max_workers=15,
    find_embedding=False,
    embedding_model='Facenet'
)

/home/mojtaba.kananisarche

2025-05-28 01:17:53.941514: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1748416673.995112 1432733 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1748416674.011754 1432733 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1748416674.046067 1432733 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1748416674.046091 1432733 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1748416674.046097 1432733 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1748416674.046101 1432733 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2025-05-28 01:17:54.057535: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1748416694.190109 1435333 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1748416694.206720 1435333 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1748416694.240262 1435333 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1748416694.240289 1435333 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1748416694.240295 1435333 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1748416694.240300 1435333 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1748416703.256097 1435333 task_runner.cc:85] GPU suport is not available: INTERNAL: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:84) egl_initializedUnable to initialize EGL
W0000 00:00:1748416703.257400 1435333 face_landmarker_graph.cc:174] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
W0000 00:00:1748416703.387297 1436098 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1748416703.436175 1436110 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
WARNING:root:New video dimensions found: 552, 552
I0000 00:00:1748416706.759917 1435333 task_runner.cc:85] GPU suport is not available: INTERNAL: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:84) egl_initializedUnable to initialize EGL
W0000 00:00:1748416706.760677 1435333 face_landmarker_graph.cc:174] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1748416707.067265 1436394 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1748416707.112609 1436406 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
I0000 00:00:1748416707.567959 1435333 task_runner.cc:85] GPU suport is not available: INTERNAL: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:84) egl_initializedUnable to initialize EGL
W0000 00:00:1748416707.569681 1435333 face_landmarker_graph.cc:174] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1748416707.851871 1436486 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1748416707.899158 1436504 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
I0000 00:00:1748416708.239855 1435333 task_runner.cc:85] GPU suport is not available: INTERNAL: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:84) egl_initializedUnable to initialize EGL
W0000 00:00:1748416708.240800 1435333 face_landmarker_graph.cc:174] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1748416708.658910 1437037 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1748416708.705224 1437051 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
I0000 00:00:1748416709.027504 1435333 task_runner.cc:85] GPU suport is not available: INTERNAL: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:84) egl_initializedUnable to initialize EGL
W0000 00:00:1748416709.029805 1435333 face_landmarker_graph.cc:174] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1748416709.269198 1437633 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1748416709.315897 1437650 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
I0000 00:00:1748416709.632860 1435333 task_runner.cc:85] GPU suport is not available: INTERNAL: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:84) egl_initializedUnable to initialize EGL
W0000 00:00:1748416709.633806 1435333 face_landmarker_graph.cc:174] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1748416709.883297 1437690 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1748416709.929250 1437703 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
I0000 00:00:1748416710.442126 1435333 task_runner.cc:85] GPU suport is not available: INTERNAL: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:84) egl_initializedUnable to initialize EGL
W0000 00:00:1748416710.443633 1435333 face_landmarker_graph.cc:174] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1748416710.689324 1437995 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1748416710.734466 1438009 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
I0000 00:00:1748416711.073890 1435333 task_runner.cc:85] GPU suport is not available: INTERNAL: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:84) egl_initializedUnable to initialize EGL
W0000 00:00:1748416711.078060 1435333 face_landmarker_graph.cc:174] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1748416711.338158 1438052 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1748416711.387436 1438069 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
I0000 00:00:1748416711.700849 1435333 task_runner.cc:85] GPU suport is not available: INTERNAL: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:84) egl_initializedUnable to initialize EGL
W0000 00:00:1748416711.701539 1435333 face_landmarker_graph.cc:174] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1748416711.935795 1438696 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1748416711.975094 1438711 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
I0000 00:00:1748416712.295863 1435333 task_runner.cc:85] GPU suport is not available: INTERNAL: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:84) egl_initializedUnable to initialize EGL
W0000 00:00:1748416712.297722 1435333 face_landmarker_graph.cc:174] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1748416712.517921 1439240 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1748416712.564620 1439253 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
I0000 00:00:1748416712.933904 1435333 task_runner.cc:85] GPU suport is not available: INTERNAL: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:84) egl_initializedUnable to initialize EGL
W0000 00:00:1748416712.936134 1435333 face_landmarker_graph.cc:174] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1748416713.174114 1439304 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1748416713.224593 1439319 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
I0000 00:00:1748416713.552787 1435333 task_runner.cc:85] GPU suport is not available: INTERNAL: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:84) egl_initializedUnable to initialize EGL
W0000 00:00:1748416713.553452 1435333 face_landmarker_graph.cc:174] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1748416713.657230 1439619 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1748416713.706100 1439632 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
I0000 00:00:1748416714.018810 1435333 task_runner.cc:85] GPU suport is not available: INTERNAL: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:84) egl_initializedUnable to initialize EGL
W0000 00:00:1748416714.020209 1435333 face_landmarker_graph.cc:174] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1748416714.152245 1439677 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1748416714.200388 1439685 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
I0000 00:00:1748416714.657119 1435333 task_runner.cc:85] GPU suport is not available: INTERNAL: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:84) egl_initializedUnable to initialize EGL
W0000 00:00:1748416714.660858 1435333 face_landmarker_graph.cc:174] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1748416714.784618 1440235 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1748416714.828876 1440249 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
I0000 00:00:1748416715.294130 1435333 task_runner.cc:85] GPU suport is not available: INTERNAL: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:84) egl_initializedUnable to initialize EGL
W0000 00:00:1748416715.296223 1435333 face_landmarker_graph.cc:174] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1748416715.412375 1440302 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1748416715.458014 1440321 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
I0000 00:00:1748416715.778196 1435333 task_runner.cc:85] GPU suport is not available: INTERNAL: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:84) egl_initializedUnable to initialize EGL
W0000 00:00:1748416715.779590 1435333 face_landmarker_graph.cc:174] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1748416715.882045 1440362 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1748416715.931671 1440373 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
I0000 00:00:1748416716.237823 1435333 task_runner.cc:85] GPU suport is not available: INTERNAL: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:84) egl_initializedUnable to initialize EGL
W0000 00:00:1748416716.238480 1435333 face_landmarker_graph.cc:174] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1748416716.363628 1440416 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1748416716.408076 1440427 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
I0000 00:00:1748416716.776115 1435333 task_runner.cc:85] GPU suport is not available: INTERNAL: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:84) egl_initializedUnable to initialize EGL
W0000 00:00:1748416716.777426 1435333 face_landmarker_graph.cc:174] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1748416716.904924 1440907 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1748416716.951276 1440922 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
I0000 00:00:1748416717.388270 1435333 task_runner.cc:85] GPU suport is not available: INTERNAL: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:84) egl_initializedUnable to initialize EGL
W0000 00:00:1748416717.390606 1435333 face_landmarker_graph.cc:174] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1748416717.489473 1440977 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1748416717.534366 1440984 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
I0000 00:00:1748416717.880995 1435333 task_runner.cc:85] GPU suport is not available: INTERNAL: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:84) egl_initializedUnable to initialize EGL
W0000 00:00:1748416717.881752 1435333 face_landmarker_graph.cc:174] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1748416718.004759 1441037 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1748416718.049198 1441052 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
I0000 00:00:1748416718.368202 1435333 task_runner.cc:85] GPU suport is not available: INTERNAL: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:84) egl_initializedUnable to initialize EGL
W0000 00:00:1748416718.368969 1435333 face_landmarker_graph.cc:174] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1748416718.469641 1441079 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1748416718.506910 1441099 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
I0000 00:00:1748416718.850889 1435333 task_runner.cc:85] GPU suport is not available: INTERNAL: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:84) egl_initializedUnable to initialize EGL
W0000 00:00:1748416718.851803 1435333 face_landmarker_graph.cc:174] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1748416718.949355 1441346 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1748416718.992783 1441366 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
I0000 00:00:1748416719.309804 1435333 task_runner.cc:85] GPU suport is not available: INTERNAL: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:84) egl_initializedUnable to initialize EGL
W0000 00:00:1748416719.311205 1435333 face_landmarker_graph.cc:174] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1748416719.424802 1441399 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1748416719.470139 1441414 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
I0000 00:00:1748416719.765987 1435333 task_runner.cc:85] GPU suport is not available: INTERNAL: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:84) egl_initializedUnable to initialize EGL
W0000 00:00:1748416719.767486 1435333 face_landmarker_graph.cc:174] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1748416719.863396 1441753 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1748416719.906968 1441774 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
I0000 00:00:1748416720.205010 1435333 task_runner.cc:85] GPU suport is not available: INTERNAL: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:84) egl_initializedUnable to initialize EGL
W0000 00:00:1748416720.206111 1435333 face_landmarker_graph.cc:174] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1748416720.342531 1441808 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

In [19]:
%cd '/home/mojtaba.kananisarche/'

from Zh.src.utils.face_detector import FaceDetector
from Zh.src.utils.video import *

/home/mojtaba.kananisarche

In [ ]:
from Zh.src.utils.face_detector import FaceDetector
from Zh.src.utils.video import *
input_video_path = '/home/mojtaba.kananisarche/Zh/data/UTA/1.2.1-raw_30fps_cropped/1_04_0_30fps_sq_cropped.mp4'
vr = VideoReader(input_video_path)
frame = vr._read_frame_at_index(15)[1]
frame = np.ascontiguousarray(frame[:10,:10])

mp_image = mp.Image(image_format=mp.ImageFormat.SRGB, data=frame)
detector = FaceDetector(False, False, 1).landmarker
detection_result = detector.detect(mp_image)
detection_result

I0000 00:00:1748421801.529906 1432733 task_runner.cc:85] GPU suport is not available: INTERNAL: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:84) egl_initializedUnable to initialize EGL
W0000 00:00:1748421801.565409 1432733 face_landmarker_graph.cc:174] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1748421801.838836 2207166 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1748421802.005444 2207166 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

FaceLandmarkerResult(face_landmarks=[], face_blendshapes=[], facial_transformation_matrixes=[])

In [56]:
mp.tasks.vision.FaceLandmarkerResult(
    face_landmarks=[],
    face_blendshapes=[],
    facial_transformation_matrixes=[]
)

FaceLandmarkerResult(face_landmarks=[], face_blendshapes=[], facial_transformation_matrixes=[])

In [2]:
import mediapipe as mp

2025-05-28 04:28:18.866870: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1748428099.601020 2287952 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1748428099.792134 2287952 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1748428102.458328 2287952 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1748428102.458400 2287952 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1748428102.458414 2287952 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1748428102.458427 2287952 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2025-05-28 04:28:22.750665: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [3]:
mp_face_mesh = mp.solutions.face_mesh

In [8]:
mp_face_mesh.FACEMESH_TESSELATION

frozenset({(18, 17),
           (82, 38),
           (8, 9),
           (456, 248),
           (167, 2),
           (303, 271),
           (69, 104),
           (253, 450),
           (41, 42),
           (315, 16),
           (73, 74),
           (339, 373),
           (258, 385),
           (105, 63),
           (219, 48),
           (304, 272),
           (236, 217),
           (231, 22),
           (85, 84),
           (365, 367),
           (237, 218),
           (243, 112),
           (436, 427),
           (409, 410),
           (248, 456),
           (330, 266),
           (136, 135),
           (88, 95),
           (394, 430),
           (107, 108),
           (118, 117),
           (439, 438),
           (442, 443),
           (260, 466),
           (115, 48),
           (342, 276),
           (121, 128),
           (200, 421),
           (113, 124),
           (132, 137),
           (23, 230),
           (343, 357),
           (443, 444),
           (62, 78),
           (26, 155),
           (228, 110),
           (432, 434),
           (364, 379),
           (325, 308),
           (424, 430),
           (36, 205),
           (363, 420),
           (21, 162),
           (328, 462),
           (419, 351),
           (366, 345),
           (193, 8),
           (363, 456),
           (183, 80),
           (307, 375),
           (94, 2),
           (333, 284),
           (17, 313),
           (185, 40),
           (44, 1),
           (291, 287),
           (411, 352),
           (20, 238),
           (59, 166),
           (272, 310),
           (420, 437),
           (387, 260),
           (130, 226),
           (51, 45),
           (175, 377),
           (202, 214),
           (353, 383),
           (339, 448),
           (291, 408),
           (466, 260),
           (264, 454),
           (457, 440),
           (355, 429),
           (96, 89),
           (128, 121),
           (187, 207),
           (360, 278),
           (306, 307),
           (446, 467),
           (165, 39),
           (337, 151),
           (168, 193),
           (73, 41),
           (318, 403),
           (263, 467),
           (283, 445),
           (74, 42),
           (201, 83),
           (65, 222),
           (37, 11),
           (429, 355),
           (272, 408),
           (179, 180),
           (100, 36),
           (158, 157),
           (438, 440),
           (358, 331),
           (281, 456),
           (136, 138),
           (314, 404),
           (417, 8),
           (34, 127),
           (367, 416),
           (180, 181),
           (426, 322),
           (419, 197),
           (457, 309),
           (215, 138),
           (242, 241),
           (33, 247),
           (53, 225),
           (126, 209),
           (467, 359),
           (224, 223),
           (271, 304),
           (97, 2),
           (183, 191),
           (202, 204),
           (95, 78),
           (246, 247),
           (177, 147),
           (357, 343),
           (65, 55),
           (116, 137),
           (135, 150),
           (382, 256),
           (199, 171),
           (298, 293),
           (16, 315),
           (204, 106),
           (149, 170),
           (150, 135),
           (403, 315),
           (61, 57),
           (205, 187),
           (44, 4),
           (358, 429),
           (277, 355),
           (438, 309),
           (42, 80),
           (236, 174),
           (128, 232),
           (302, 268),
           (313, 314),
           (240, 64),
           (291, 375),
           (260, 387),
           (113, 225),
           (107, 65),
           (247, 225),
           (346, 347),
           (44, 125),
           (378, 379),
           (466, 263),
           (250, 459),
           (50, 205),
           (111, 35),
           (76, 77),
           (122, 193),
           (209, 198),
           (201, 194),
           (408, 407),
           (285, 336),
           (2, 393),
           (243, 190),
           (336, 9),
           (234, 227),
           (293, 276),
           (221, 28),
           (57, 185),
           (217, 174),
           (131, 134),
           (344, 278),
           (343, 399),
           (28, 158),
           (128, 245),
           (463, 464),
           (443, 257),
           (394, 364),
           (164, 167),
           (10, 109),
           (196, 236),
           (429, 358),
           (174, 217),
           (452, 341),
           (2, 370),
           (84, 180),
           (320, 307),
           (0, 37),
           (250, 328),
           (101, 119),
           (41, 74),
           (399, 456),
           (13, 12),
           (218, 115),
           (343, 412),
           (16, 17),
           (55, 8),
           (107, 55),
           (153, 22),
           (440, 344),
           (393, 269),
           (364, 434),
           (38, 41),
           (296, 336),
           (68, 63),
           (402, 317),
           (456, 437),
           (253, 374),
           (254, 339),
           (67, 104),
           (392, 309),
           (145, 23),
           (63, 70),
           (403, 318),
           (127, 234),
           (415, 292),
           (54, 21),
           (168, 6),
           (72, 38),
           (204, 194),
           (83, 84),
           (282, 293),
           (302, 271),
           (120, 231),
           (434, 427),
           (320, 405),
           (426, 423),
           (441, 286),
           (145, 144),
           (341, 464),
           (208, 200),
           (250, 462),
           (112, 232),
           (258, 286),
           (418, 424),
           (160, 159),
           (286, 384),
           (421, 200),
           (274, 1),
           (200, 201),
           (166, 59),
           (111, 123),
           (211, 210),
           (330, 347),
           (422, 430),
           (214, 135),
           (280, 346),
           (107, 9),
           (265, 446),
           (244, 243),
           (417, 351),
           (110, 163),
           (450, 348),
           (396, 377),
           (245, 244),
           (83, 182),
           (8, 417),
           (451, 349),
           (203, 98),
           (376, 435),
           (101, 50),
           (345, 447),
           (412, 357),
           (238, 241),
           (90, 77),
           (369, 395),
           (276, 353),
           (253, 449),
           (359, 467),
           (279, 358),
           (315, 15),
           (433, 416),
           (299, 336),
           (46, 156),
           (167, 37),
           (460, 290),
           (311, 310),
           (410, 432),
           (357, 277),
           (35, 226),
           (304, 271),
           (189, 55),
           (314, 315),
           (108, 67),
           (1, 4),
           (4, 275),
           (205, 36),
           (156, 143),
           (436, 426),
           (223, 53),
           (461, 370),
           (23, 144),
           (29, 224),
           (244, 112),
           (348, 349),
           (340, 345),
           (122, 6),
           (401, 361),
           (228, 24),
           (252, 381),
           (37, 164),
           (192, 187),
           (177, 58),
           (410, 409),
           (316, 402),
           (381, 382),
           (429, 279),
           (140, 176),
           (26, 154),
           (434, 394),
           (52, 63),
           (79, 166),
           (72, 41),
           (71, 162),
           (244, 233),
           (222, 65),
           (214, 210),
           (354, 370),
           (140, 32),
           (30, 160),
           (212, 57),
           (444, 443),
           (7, 33),
           (301, 251),
           (213, 138),
           (170, 176),
           (17, 83),
           (268, 302),
           (32, 211),
           (331, 358),
           (186, 40),
           (105, 52),
           (457, 354),
           (395, 379),
           (375, 321),
           (325, 320),
           (317, 316),
           (274, 354),
           (96, 88),
           (15, 14),
           (467, 260),
           (232, 128),
           (404, 320),
           (350, 349),
           (342, 265),
           (74, 185),
           (314, 17),
           (146, 61),
           (247, 113),
           (405, 321),
           (256, 341),
           (283, 444),
           (409, 291),
           (74, 41),
           (78, 191),
           (245, 188),
           (103, 104),
           (19, 370),
           (19, 141),
           (280, 411),
           (220, 131),
           (85, 86),
           (372, 265),
           (237, 220),
           (204, 43),
           (118, 119),
           (210, 202),
           (290, 460),
           (450, 449),
           (83, 18),
           (197, 3),
           (315, 404),
           (461, 458),
           (169, 170),
           (246, 161),
           (32, 201),
           (236, 196),
           (409, 304),
           (295, 282),
           (395, 369),
           (181, 180),
           (353, 372),
           (139, 34),
           (432, 436),
           (370, 461),
           (184, 42),
           (96, 78),
           (113, 247),
           (326, 391),
           (147, 123),
           (126, 100),
           (205, 101),
           (452, 350),
           (71, 21),
           (16, 85),
           (297, 333),
           (136, 150),
           (260, 445),
           (34, 139),
           (46, 113),
           (17, 315),
           (104, 54),
           (383, 372),
           (417, 285),
           (150, 170),
           (20, 60),
           (39, 73),
           (45, 4),
           (438, 344),
           (37, 0),
           (177, 123),
           (336, 296),
           (102, 129),
           (134, 198),
           (175, 199),
           (302, 303),
           (293, 334),
           (87, 86),
           (99, 240),
           (240, 99),
           (364, 394),
           (64, 102),
           (256, 452),
           (337, 297),
           (383, 264),
           (141, 242),
           (188, 174),
           (120, 119),
           (207, 187),
           (467, 263),
           (30, 225),
           (131, 48),
           (425, 266),
           (121, 120),
           (85, 17),
           (28, 157),
           (337, 9),
           (342, 353),
           (154, 153),
           (361, 366),
           (227, 137),
           (52, 105),
           (118, 50),
           (217, 209),
           (424, 422),
           (249, 390),
           (196, 6),
           (26, 232),
           (287, 273),
           (210, 169),
           (350, 329),
           (62, 191),
           (276, 300),
           (248, 281),
           (368, 383),
           (427, 432),
           (453, 341),
           (372, 353),
           (357, 453),
           (101, 118),
           (321, 307),
           (407, 310),
           (266, 371),
           (420, 429),
           (306, 407),
           (253, 252),
           (224, 225),
           (112, 133),
           (356, 264),
           (370, 19),
           (254, 253),
           (219, 115),
           (225, 46),
           (124, 143),
           (289, 439),
           (13, 312),
           (253, 373),
           (154, 22),
           (319, 318),
           (363, 281),
           (169, 150),
           (355, 277),
           (354, 461),
           (267, 164),
           (320, 319),
           (39, 40),
           (277, 357),
           (63, 105),
           (189, 244),
           (34, 227),
           (120, 230),
           (293, 301),
           (60, 99),
           (72, 73),
           (283, 293),
           (307, 321),
           (321, 405),
           (93, 132),
           (183, 62),
           (408, 409),
           (151, 338),
           (186, 216),
           (151, 109),
           (245, 122),
           (189, 221),
           (335, 424),
           (442, 258),
           (441, 442),
           (114, 47),
           (173, 133),
           (452, 451),
           (106, 43),
           (305, 289),
           (362, 414),
           (443, 259),
           (294, 279),
           (258, 442),
           (57, 43),
           (256, 252),
           (259, 443),
           (46, 70),
           (420, 360),
           (126, 142),
           (371, 355),
           (112, 244),
           (431, 369),
           (47, 114),
           (100, 126),
           (12, 13),
           (91, 77),
           (23, 22),
           (51, 4),
           (48, 115),
           (254, 449),
           (160, 27),
           (353, 342),
           (434, 416),
           (266, 423),
           (4, 274),
           (316, 15),
           (4, 45),
           (24, 23),
           (80, 183),
           (341, 453),
           (109, 67),
           (174, 196),
           (66, 105),
           (89, 88),
           (29, 223),
           (164, 2),
           (462, 370),
           (328, 290),
           (400, 395),
           (181, 91),
           (252, 380),
           (24, 144),
           (313, 18),
           (354, 19),
           (185, 61),
           (90, 89),
           (116, 227),
           (168, 417),
           (329, 371),
           (156, 34),
           (450, 252),
           (8, 285),
           (164, 267),
           (168, 8),
           (153, 145),
           (361, 323),
           (285, 413),
           (346, 280),
           (117, 228),
           (130, 247),
           (140, 211),
           (426, 425),
           (53, 63),
           (245, 233),
           (2, 97),
           (216, 206),
           (195, 3),
           (459, 458),
           (178, 179),
           (276, 342),
           (235, 75),
           (399, 412),
           (185, 74),
           (170, 211),
           (465, 357),
           (222, 221),
           (75, 59),
           (229, 117),
           (422, 432),
           (327, 423),
           (275, 4),
           (12, 268),
           (267, 0),
           (64, 49),
           (244, 245),
           (115, 131),
           (376, 401),
           (171, 32),
           (161, 247),
           (26, 22),
           (454, 356),
           (166, 218),
           (420, 363),
           (233, 128),
           (193, 55),
           (278, 279),
           (405, 320),
           (334, 296),
           (279, 360),
           (201, 32),
           (220, 45),
           (315, 17),
           (354, 274),
           (167, 39),
           (51, 236),
           (3, 196),
           (108, 69),
           (128, 47),
           (266, 426),
           (99, 20),
           (259, 387),
           (137, 132),
           (273, 321),
           (394, 431),
           (285, 295),
           (437, 429),
           (83, 17),
           (315, 403),
           (449, 254),
           (461, 457),
           (260, 467),
           (359, 446),
           (184, 185),
           (411, 376),
           (263, 249),
           (462, 458),
           (215, 172),
           (52, 65),
           (247, 161),
           (191, 80),
           (424, 431),
           (36, 206),
           (262, 369),
           (296, 282),
           (396, 369),
           (134, 220),
           (335, 273),
           (214, 212),
           (193, 189),
           (364, 416),
           (270, 409),
           (444, 445),
           (229, 228),
           (330, 280),
           (456, 419),
           (260, 444),
           (188, 196),
           (406, 418),
           (30, 247),
           (398, 414),
           (17, 314),
           (210, 214),
           (17, 85),
           (423, 358),
           (63, 52),
           (19, 274),
           (272, 311),
           (50, 118),
           (14, 15),
           (180, 84),
           (5, 195),
           (240, 98),
           (439, 344),
           (256, 451),
           (123, 187),
           (15, 16),
           (96, 90),
           (141, 241),
           (6, 196),
           (360, 279),
           (347, 346),
           (198, 217),
           (318, 319),
           (358, 355),
           (418, 406),
           (115, 219),
           (190, 133),
           (77, 76),
           (110, 24),
           (48, 49),
           (80, 81),
           (333, 298),
           (353, 276),
           (141, 97),
           (373, 254),
           (69, 108),
           (418, 262),
           (463, 413),
           (294, 455),
           (21, 68),
           (81, 82),
           (118, 229),
           (284, 298),
           (371, 266),
           (384, 385),
           (231, 26),
           (395, 394),
           (322, 410),
           (248, 195),
           (361, 401),
           (214, 202),
           (119, 230),
           (111, 226),
           (43, 91),
           (383, 276),
           (168, 351),
           (449, 450),
           (314, 405),
           (55, 65),
           (182, 106),
           (394, 434),
           (393, 326),
           (210, 204),
           (211, 169),
           (450, 451),
           (203, 165),
           (22, 153),
           (143, 34),
           (409, 270),
           (7, 110),
           (448, 261),
           (213, 215),
           (371, 423),
           (64, 235),
           (9, 336),
           (278, 344),
           (89, 179),
           (236, 198),
           (336, 285),
           (181, 182),
           (194, 201),
           (66, 52),
           (151, 10),
           (123, 177),
           (341, 256),
           (455, 278),
           (326, 393),
           (257, 442),
           (269, 267),
           (203, 142),
           (238, 20),
           (268, 271),
           (254, 373),
           (414, 362),
           (305, 455),
           (357, 465),
           (189, 243),
           (42, 81),
           (286, 441),
           (179, 86),
           (217, 198),
           (84, 83),
           (456, 363),
           (214, 192),
           (326, 370),
           (107, 66),
           (247, 226),
           (88, 89),
           (27, 222),
           (120, 121),
           (99, 98),
           (279, 294),
           (151, 108),
           (75, 235),
           (150, 149),
           (388, 466),
           (129, 126),
           (447, 372),
           (366, 447),
           (70, 156),
           (56, 221),
           (171, 208),
           (190, 221),
           (28, 159),
           (435, 397),
           (54, 68),
           (368, 264),
           (214, 169),
           (294, 278),
           (221, 65),
           (206, 165),
           (29, 160),
           (281, 195),
           (33, 130),
           (447, 264),
           (298, 284),
           (278, 455),
           (201, 208),
           (427, 434),
           (360, 344),
           (321, 273),
           (379, 394),
           (265, 372),
           (274, 457),
           (101, 120),
           (182, 194),
           (227, 116),
           (253, 254),
           (352, 376),
           (4, 44),
           (351, 417),
           (350, 452),
           (283, 282),
           (194, 204),
           (55, 9),
           (106, 91),
           (410, 322),
           (48, 235),
           (316, 315),
           (367, 397),
           (427, 411),
           (319, 320),
           (193, 244),
           (398, 384),
           (331, 294),
           (313, 17),
           (297, 338),
           (164, 37),
           (403, 319),
           (349, 348),
           (47, 126),
           (8, 55),
           (147, 213),
           (320, 321),
           (227, 93),
           (134, 131),
           (44, 237),
           (393, 391),
           (439, 278),
           (451, 252),
           (120, 232),
           (287, 409),
           (221, 55),
           (385, 386),
           (347, 280),
           (57, 212),
           (58, 177),
           (257, 386),
           (216, 205),
           (208, 201),
           (386, 387),
           (459, 457),
           (137, 177),
           (391, 322),
           (49, 64),
           (55, 107),
           (308, 324),
           (372, 345),
           (11, 37),
           (431, 394),
           (171, 175),
           (330, 348),
           (156, 46),
           (11, 302),
           (280, 347),
           (452, 453),
           (352, 366),
           (12, 38),
           (64, 48),
           (22, 231),
           (414, 463),
           (448, 339),
           (422, 287),

In [17]:
frame[0:5,0:5,0:5]

array([[[90, 98, 97],
        [90, 98, 97],
        [90, 98, 97],
        [90, 98, 97],
        [90, 98, 97]],

       [[90, 98, 97],
        [90, 98, 97],
        [90, 98, 97],
        [90, 98, 97],
        [90, 98, 97]],

       [[90, 98, 97],
        [90, 98, 97],
        [90, 98, 97],
        [90, 98, 97],
        [90, 98, 97]],

       [[90, 98, 97],
        [90, 98, 97],
        [90, 98, 97],
        [90, 98, 97],
        [90, 98, 97]],

       [[90, 98, 97],
        [90, 98, 97],
        [90, 98, 97],
        [90, 98, 97],
        [90, 98, 97]]], dtype=uint8)

In [1]:
%cd '/home/mojtaba.kananisarche/'

from Zh.src.utils.file_folder import copy_directory_structure
from Zh.src.utils.video import *
from Zh.src.preprocess.preprocessing import _remove_background_from_video_one_file, remove_background_from_video, _remove_background_from_video_one_frame
# import pandas as pd
# import numpy as np
# import os
# import logging
# import json

/home/mojtaba.kananisarche

2025-05-27 21:01:44.205746: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1748401304.910641 2245852 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1748401305.178854 2245852 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1748401307.932703 2245852 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1748401307.932761 2245852 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1748401307.932776 2245852 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1748401307.932788 2245852 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2025-05-27 21:01:48.268495: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [2]:
input_video_path = '/home/mojtaba.kananisarche/Zh/data/UTA/1.2.1-raw_30fps_cropped/1_04_0_30fps_sq_cropped.mp4'
vr = VideoReader(input_video_path)

In [5]:
vr._read_frame_at_index(245)[1]

array([[[ 90,  98,  97],
        [ 90,  98,  97],
        [ 90,  98,  97],
        ...,
        [ 84,  88,  90],
        [ 84,  88,  90],
        [ 84,  88,  90]],

       [[ 90,  98,  97],
        [ 90,  98,  97],
        [ 90,  98,  97],
        ...,
        [ 84,  88,  90],
        [ 84,  88,  90],
        [ 84,  88,  90]],

       [[ 90,  98,  97],
        [ 90,  98,  97],
        [ 90,  98,  97],
        ...,
        [ 84,  88,  90],
        [ 84,  88,  90],
        [ 84,  88,  90]],

       ...,

       [[128, 136, 133],
        [128, 136, 133],
        [125, 133, 130],
        ...,
        [112, 134, 124],
        [112, 134, 124],
        [112, 134, 124]],

       [[126, 134, 131],
        [126, 134, 131],
        [124, 132, 129],
        ...,
        [111, 133, 123],
        [111, 133, 123],
        [111, 133, 123]],

       [[126, 134, 131],
        [126, 134, 131],
        [124, 132, 129],
        ...,
        [111, 133, 123],
        [111, 133, 123],
        [111, 133, 123]]], dtype=uint8)

In [4]:
vr.next_frame()

array([[[102, 106, 108],
        [102, 106, 108],
        [102, 106, 108],
        ...,
        [ 72,  63,  60],
        [ 68,  59,  56],
        [ 66,  57,  54]],

       [[102, 106, 108],
        [102, 106, 108],
        [102, 106, 108],
        ...,
        [ 72,  63,  60],
        [ 68,  59,  56],
        [ 66,  57,  54]],

       [[102, 106, 108],
        [102, 106, 108],
        [102, 106, 108],
        ...,
        [ 73,  64,  61],
        [ 69,  60,  57],
        [ 67,  58,  55]],

       ...,

       [[108, 108, 108],
        [108, 108, 108],
        [108, 108, 108],
        ...,
        [189, 191, 184],
        [185, 187, 180],
        [182, 184, 177]],

       [[108, 108, 108],
        [108, 108, 108],
        [108, 108, 108],
        ...,
        [181, 183, 176],
        [180, 182, 175],
        [179, 181, 174]],

       [[108, 108, 108],
        [108, 108, 108],
        [108, 108, 108],
        ...,
        [176, 178, 171],
        [175, 177, 170],
        [176, 178, 171]]], dtype=uint8)

In [2]:
_remove_background_from_video_one_file(
    input_video_path = '/home/mojtaba.kananisarche/Zh/data/UTA/1.2.1-raw_30fps_cropped/1_04_0_30fps_sq_cropped.mp4',
    output_folder_path = '/home/mojtaba.kananisarche/Zh/temp',
)

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1747871711.269416 2653192 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1747871711.296783 2692072 gl_context.cc:369] GL version: 3.2 (OpenGL ES 3.2 Mesa 23.1.4), renderer: llvmpipe (LLVM 17.0.6, 256 bits)
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
W0000 00:00:1747871711.374664 2691976 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

Processing video: /home/mojtaba.kananisarche/Zh/data/UTA/1.2.1-raw_30fps_cropped/1_04_0_30fps_sq_cropped.mp4
Saving output to: /home/mojtaba.kananisarche/Zh/temp/1_04_0_30fps_sq_cropped_bgremoved.mp4
Dimensions: 320x320, FPS: 30
Processing complete. Total frames processed: 18437
Output video saved to: /home/mojtaba.kananisarche/Zh/temp/1_04_0_30fps_sq_cropped_bgremoved.mp4

In [4]:
from Zh.src.utils.common import save_obj


def copy_video_split_info(source_dir, target_dir):
    """
    Traverses all files in the source directory and its subdirectories.
    If a file is a CSV, it reads it using pandas and saves it as a NPY file
    in the corresponding subdirectory in the target folder.

    Args:
        source_dir (str): Path to the source directory
        target_dir (str): Path to the target directory where NPY files will be saved

    Returns:
        tuple: (int, int) - Count of processed files and count of errors
    """
    # Check if source directory exists

    copy_directory_structure(source_dir=source_dir, target_dir=target_dir)

    processed_count = 0
    error_count = 0

    # Walk through all directories and files in source_dir
    for root, _, files in os.walk(source_dir):
        # Calculate relative path and target subdir to maintain directory structure
        relative_path = os.path.relpath(root, source_dir)
        target_subdir = os.path.join(target_dir, relative_path)

        # Process each file in current directory
        for file in files:
            source_file = os.path.join(root, file)
            target_file = os.path.join(target_subdir, file)

            if file == "split_info.json":
                try:
                    with open(source_file, 'r') as json_file:
                        j = json.load(json_file)

                    for fold in j:
                        fold['input_paths'] = fold['output_paths'].copy()
                        splits = ['train', 'test', 'val']
                        for split in splits:
                            fold['output_paths'][split] = [path.replace(source_dir, target_dir).replace('.csv', '.npy') for path in fold['output_paths'][split]]
                
                    save_obj(j, target_file, 'json')
                    print(f"Saved as: {target_file}")
                    processed_count += 1

                except Exception as e:
                    print(f"Error processing {source_file}: {str(e)}")
                    error_count += 1
                
            if file == "video_info.csv":
                try:
                    # Read CSV using pandas
                    print(f"Processing: {source_file}")

                    df = pd.read_csv(source_file)
                    df['path'] = df['path'].apply(lambda x: x.replace(source_dir, target_dir).replace('.csv', '.npy'))
                
                    df.to_csv(target_file, index=False)
                    print(f"Saved as: {target_file}")
                    processed_count += 1

                except Exception as e:
                    print(f"Error processing {source_file}: {str(e)}")
                    error_count += 1


    print(f"Completed: {processed_count} files processed, {error_count} errors")

In [5]:
source_dir='/work/long_lab/Mojtaba/data/UTA/1.3.3-augmented_embedded_preprocessed_normalized'
target_dir='/work/long_lab/Mojtaba/data/UTA/1.3.4-augmented_embedded_preprocessed_normalized_npy'

copy_video_split_info(source_dir=source_dir, 
                      target_dir=target_dir)

Saved as: /work/long_lab/Mojtaba/data/UTA/1.3.4-augmented_embedded_preprocessed_normalized_npy/./split_info.json
Processing: /work/long_lab/Mojtaba/data/UTA/1.3.3-augmented_embedded_preprocessed_normalized/2/video_info.csv
Saved as: /work/long_lab/Mojtaba/data/UTA/1.3.4-augmented_embedded_preprocessed_normalized_npy/2/video_info.csv
Processing: /work/long_lab/Mojtaba/data/UTA/1.3.3-augmented_embedded_preprocessed_normalized/5/video_info.csv
Saved as: /work/long_lab/Mojtaba/data/UTA/1.3.4-augmented_embedded_preprocessed_normalized_npy/5/video_info.csv
Processing: /work/long_lab/Mojtaba/data/UTA/1.3.3-augmented_embedded_preprocessed_normalized/9/video_info.csv
Saved as: /work/long_lab/Mojtaba/data/UTA/1.3.4-augmented_embedded_preprocessed_normalized_npy/9/video_info.csv
Processing: /work/long_lab/Mojtaba/data/UTA/1.3.3-augmented_embedded_preprocessed_normalized/4/video_info.csv
Saved as: /work/long_lab/Mojtaba/data/UTA/1.3.4-augmented_embedded_preprocessed_normalized_npy/4/video_info.csv
Processing: /work/long_lab/Mojtaba/data/UTA/1.3.3-augmented_embedded_preprocessed_normalized/7/video_info.csv
Saved as: /work/long_lab/Mojtaba/data/UTA/1.3.4-augmented_embedded_preprocessed_normalized_npy/7/video_info.csv
Processing: /work/long_lab/Mojtaba/data/UTA/1.3.3-augmented_embedded_preprocessed_normalized/1/video_info.csv
Saved as: /work/long_lab/Mojtaba/data/UTA/1.3.4-augmented_embedded_preprocessed_normalized_npy/1/video_info.csv
Processing: /work/long_lab/Mojtaba/data/UTA/1.3.3-augmented_embedded_preprocessed_normalized/0/video_info.csv
Saved as: /work/long_lab/Mojtaba/data/UTA/1.3.4-augmented_embedded_preprocessed_normalized_npy/0/video_info.csv
Processing: /work/long_lab/Mojtaba/data/UTA/1.3.3-augmented_embedded_preprocessed_normalized/8/video_info.csv
Saved as: /work/long_lab/Mojtaba/data/UTA/1.3.4-augmented_embedded_preprocessed_normalized_npy/8/video_info.csv
Processing: /work/long_lab/Mojtaba/data/UTA/1.3.3-augmented_embedded_preprocessed_normalized/6/video_info.csv
Saved as: /work/long_lab/Mojtaba/data/UTA/1.3.4-augmented_embedded_preprocessed_normalized_npy/6/video_info.csv
Processing: /work/long_lab/Mojtaba/data/UTA/1.3.3-augmented_embedded_preprocessed_normalized/3/video_info.csv
Saved as: /work/long_lab/Mojtaba/data/UTA/1.3.4-augmented_embedded_preprocessed_normalized_npy/3/video_info.csv
Processing: /work/long_lab/Mojtaba/data/UTA/1.3.3-augmented_embedded_preprocessed_normalized/11/video_info.csv
Saved as: /work/long_lab/Mojtaba/data/UTA/1.3.4-augmented_embedded_preprocessed_normalized_npy/11/video_info.csv
Processing: /work/long_lab/Mojtaba/data/UTA/1.3.3-augmented_embedded_preprocessed_normalized/10/video_info.csv
Saved as: /work/long_lab/Mojtaba/data/UTA/1.3.4-augmented_embedded_preprocessed_normalized_npy/10/video_info.csv
Processing: /work/long_lab/Mojtaba/data/UTA/1.3.3-augmented_embedded_preprocessed_normalized/17/video_info.csv
Saved as: /work/long_lab/Mojtaba/data/UTA/1.3.4-augmented_embedded_preprocessed_normalized_npy/17/video_info.csv
Processing: /work/long_lab/Mojtaba/data/UTA/1.3.3-augmented_embedded_preprocessed_normalized/14/video_info.csv
Saved as: /work/long_lab/Mojtaba/data/UTA/1.3.4-augmented_embedded_preprocessed_normalized_npy/14/video_info.csv
Processing: /work/long_lab/Mojtaba/data/UTA/1.3.3-augmented_embedded_preprocessed_normalized/13/video_info.csv
Saved as: /work/long_lab/Mojtaba/data/UTA/1.3.4-augmented_embedded_preprocessed_normalized_npy/13/video_info.csv
Processing: /work/long_lab/Mojtaba/data/UTA/1.3.3-augmented_embedded_preprocessed_normalized/18/video_info.csv
Saved as: /work/long_lab/Mojtaba/data/UTA/1.3.4-augmented_embedded_preprocessed_normalized_npy/18/video_info.csv
Processing: /work/long_lab/Mojtaba/data/UTA/1.3.3-augmented_embedded_preprocessed_normalized/16/video_info.csv
Saved as: /work/long_lab/Mojtaba/data/UTA/1.3.4-augmented_embedded_preprocessed_normalized_npy/16/video_info.csv
Processing: /work/long_lab/Mojtaba/data/UTA/1.3.3-augmented_embedded_preprocessed_normalized/19/video_info.csv
Saved as: /work/long_lab/Mojtaba/data/UTA/1.3.4-augmented_embedded_preprocessed_normalized_npy/19/video_info.csv
Processing: /work/long_lab/Mojtaba/data/UTA/1.3.3-augmented_embedded_preprocessed_normalized/15/video_info.csv
Saved as: /work/long_lab/Mojtaba/data/UTA/1.3.4-augmented_embedded_preprocessed_normalized_npy/15/video_info.csv
Processing: /work/long_lab/Mojtaba/data/UTA/1.3.3-augmented_embedded_preprocessed_normalized/12/video_info.csv
Saved as: /work/long_lab/Mojtaba/data/UTA/1.3.4-augmented_embedded_preprocessed_normalized_npy/12/video_info.csv
Completed: 21 files processed, 0 errors

In [ ]:
for fold in df:
    fold['input_paths'] = fold['output_paths'].copy()
    splits = ['train', 'test', 'val']
    for split in splits:
        fold['output_paths'][split] = [path.replace(source_dir, target_dir).replace('.csv', '.npy') for path in fold['output_paths'][split]]

In [70]:
df[0]['input_paths']['test'][0]

'/work/long_lab/Mojtaba/data/UTA/1.3.4-augmented_embedded_preprocessed_normalized_npy/0/brightness_alpha0.8_beta-10/1_01_0_30fps_brightness_alpha0.8_beta-10_preprocessed.npy'

In [71]:
df[0]['output_paths']['test'][0]

'/work/long_lab/Mojtaba/data/UTA/1.3.4-augmented_embedded_preprocessed_normalized_npy/0/brightness_alpha0.8_beta-10/1_01_0_30fps_brightness_alpha0.8_beta-10_preprocessed.npy'

In [38]:
df[0]['input_paths']['test'][0]

'/work/long_lab/Mojtaba/data/UTA/1.3.4-augmented_embedded_preprocessed_normalized_npy/0/brightness_alpha0.8_beta-10/1_01_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv'

In [51]:
df[0]['input_paths']['test'][0]

'/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_01_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv'

In [52]:
df[0]['output_paths']['test'][0]

'/work/long_lab/Mojtaba/data/UTA/1.3.3-augmented_embedded_preprocessed_normalized/0/brightness_alpha0.8_beta-10/1_01_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv'

In [2]:
%cd '/home/mojtaba.kananisarche/'

from Zh.src.utils.common import save_obj
import os

target_dir='/work/long_lab/Mojtaba/data/UTA/1.3.4-augmented_embedded_preprocessed_normalized_npy'
save_obj(obj=[1,2,3], output_path=os.path.join(target_dir, 'columns.json'), file_type='json')

/home/mojtaba.kananisarche

In [16]:
df = pd.read_csv('/work/long_lab/Mojtaba/data/UTA/1.3.3-augmented_embedded_preprocessed_normalized/1/brightness_alpha0.8_beta-10/1_01_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv')

In [23]:
sorted(list(df.select_dtypes(include='number').columns))

['f_0',
 'f_1',
 'f_10',
 'f_100',
 'f_101',
 'f_102',
 'f_103',
 'f_104',
 'f_105',
 'f_106',
 'f_107',
 'f_108',
 'f_109',
 'f_11',
 'f_110',
 'f_111',
 'f_112',
 'f_113',
 'f_114',
 'f_115',
 'f_116',
 'f_117',
 'f_118',
 'f_119',
 'f_12',
 'f_120',
 'f_121',
 'f_122',
 'f_123',
 'f_124',
 'f_125',
 'f_126',
 'f_127',
 'f_13',
 'f_14',
 'f_15',
 'f_16',
 'f_17',
 'f_18',
 'f_19',
 'f_2',
 'f_20',
 'f_21',
 'f_22',
 'f_23',
 'f_24',
 'f_25',
 'f_26',
 'f_27',
 'f_28',
 'f_29',
 'f_3',
 'f_30',
 'f_31',
 'f_32',
 'f_33',
 'f_34',
 'f_35',
 'f_36',
 'f_37',
 'f_38',
 'f_39',
 'f_4',
 'f_40',
 'f_41',
 'f_42',
 'f_43',
 'f_44',
 'f_45',
 'f_46',
 'f_47',
 'f_48',
 'f_49',
 'f_5',
 'f_50',
 'f_51',
 'f_52',
 'f_53',
 'f_54',
 'f_55',
 'f_56',
 'f_57',
 'f_58',
 'f_59',
 'f_6',
 'f_60',
 'f_61',
 'f_62',
 'f_63',
 'f_64',
 'f_65',
 'f_66',
 'f_67',
 'f_68',
 'f_69',
 'f_7',
 'f_70',
 'f_71',
 'f_72',
 'f_73',
 'f_74',
 'f_75',
 'f_76',
 'f_77',
 'f_78',
 'f_79',
 'f_8',
 'f_80',
 'f_81',
 'f_82',
 'f_83',
 'f_84',
 'f_85',
 'f_86',
 'f_87',
 'f_88',
 'f_89',
 'f_9',
 'f_90',
 'f_91',
 'f_92',
 'f_93',
 'f_94',
 'f_95',
 'f_96',
 'f_97',
 'f_98',
 'f_99',
 'fold',
 'frame',
 'subject_id',
 'target']

In [25]:
df[list(df.select_dtypes(include='number').columns)]

,frame,fold,subject_id,target,f_0,f_1,f_2,f_3,f_4,f_5,...,f_118,f_119,f_120,f_121,f_122,f_123,f_124,f_125,f_126,f_127
0,0,1,1,6.5,2.037477,1.471431,-0.382321,-0.450421,1.112900,0.363175,...,1.636705,-2.361421,2.723469,1.194544,0.717596,-0.447604,0.445552,-0.411543,-1.544169,-0.134815
1,1,1,1,6.5,1.620213,1.262559,-0.162949,-0.600908,1.094582,0.348699,...,1.414277,-2.180601,2.848324,1.221342,0.637258,-0.503358,0.238512,-0.464812,-1.691023,-0.200037
2,2,1,1,6.5,1.736541,1.149817,-0.021003,-0.437379,1.558618,0.282279,...,0.965733,-2.150860,2.532386,1.550128,0.856180,-0.512461,0.267554,-0.318584,-1.335417,-0.248954
3,3,1,1,6.5,1.627799,1.155750,-0.002233,-0.341067,1.608685,0.305270,...,0.986625,-2.146102,2.633356,1.457367,0.764795,-0.543183,0.223523,-0.302917,-1.439793,-0.418724
4,4,1,1,6.5,1.655617,1.166431,0.199543,-0.475502,1.192274,0.180945,...,0.941156,-1.933163,2.459644,1.319256,0.789901,-0.623969,0.333132,0.044897,-1.410665,-0.253750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17981,17981,1,1,6.5,1.653088,1.488045,-0.533653,0.081301,1.834597,-0.073667,...,1.474492,-2.844401,2.720212,1.200728,0.773833,-0.702480,0.763137,-0.421988,-0.932479,-0.200996
17982,17982,1,1,6.5,1.759301,1.334952,-0.681465,-0.091258,1.575714,0.267802,...,1.441312,-2.905071,2.689812,1.042004,0.777850,-0.559112,0.706927,-0.420944,-1.089042,-0.278687
17983,17983,1,1,6.5,1.713781,1.311217,-0.591136,-0.116339,1.608685,0.166469,...,1.421650,-2.871762,2.878724,1.089415,0.697512,-0.643312,0.705053,-0.471079,-1.136376,-0.269096
17984,17984,1,1,6.5,1.460894,1.070303,-0.771795,0.021106,1.656310,0.211601,...,1.497841,-3.002618,2.596442,1.223403,0.821032,-0.538631,0.553287,-0.409455,-1.112102,-0.310339
17985,17985,1,1,6.5,1.603775,1.162871,-0.565327,-0.104300,1.366898,0.219264,...,1.534708,-2.982395,2.517186,0.949243,0.646296,-0.626245,0.519561,-0.162956,-1.171572,-0.246076

In [ ]:
# path = "/home/mojtaba.kananisarche/Zh/outputs/2025-04-20|09:08:09|RNN_FACENET_5CV"
# data =table_results(
# results_directory_path  = path,
# output_directory_path   = None,
# output_file_path_prefix = 'results',
# cmap                    = "Blues",
# reverse_cmap            = False,
# header_1_bg_color       = 'silver',
# header_1_text_color     = 'black',
# header_2_bg_color       = 'darkgrey',
# header_2_text_color     = 'black',
# maximum_tries           = 1,
# slice_or_video          = 'video', #slice, video
# video_voting_method     = 'class_average', #majority, class_average, average
# height                  = 2,
# width                   = 5,
# )

Try Number 0 Succeeded.

In [ ]:
# data = confusion_matrix_results(
#     results_directory_path  = path,
#     unique_classes          = [2, 6.5, 8.5],
#     output_directory_path   = None,
#     output_file_name_prefix = "results",
#     slice_or_video          = 'slice',     #slice,    video
#     video_voting_method     = 'None',   #majority, class_average, average
#     index                   = -1,          # positive for any index and negative for all
#     split                   = "all",       # train,   val,           test, all
#     cmap                    = "Blues",
#     maximum_tries           = 5,
#     corner_text_color       = "white",
#     corner_bg_color         = "IndianRed",
#     pred_true_text_color    = "black",
#     pred_true_bg_color      = "silver",
#     labels_bg_color         = "beige",
#     labels_text_color       = "black",
#     height                  = 5,
#     width                   = None,
# )

split - train
Try Number 0 Succeeded.
split - test
Try Number 0 Succeeded.
split - val
Try Number 0 Succeeded.

In [ ]:
%cd '/home/mojtaba.kananisarche/Zh'
from typing import List, Optional, Tuple
import os
import json

def apply_normalizer_one_file(
    train_val_test_file_path : str,
    output_directory_path: str):

    import pickle
    from src.utils.file_folder import create_folders

    index = train_val_test_file_path['index']
    all_splits_paths = (train_val_test_file_path['paths']['test'] + 
                        train_val_test_file_path['paths']['val'] + 
                        train_val_test_file_path['paths']['train'])
    
    origin_directory_path = os.path.commonpath(all_splits_paths)
    origin_directory_subfolders_path = list(set([os.path.dirname(file_path) for file_path in all_splits_paths]))    
    output_directory_subfolders_path = [folder_path.replace(origin_directory_path, output_directory_path) 
                                        for folder_path in origin_directory_subfolders_path]

    create_folders(output_directory_subfolders_path)

    with open(os.path.join(output_directory_path, f"{index}_normalizer.pkl"), "rb") as file:
        scaler = pickle.load(file)

    for file_path in all_splits_paths:
        print(f"{index} - {file_path}")
        
        data = pd.read_csv(file_path)
        scaled = pd.DataFrame(scaler.transform(data[scaler.feature_names_in_]), 
                              columns = scaler.feature_names_in_)
        rest = data[data.columns.difference(scaler.feature_names_in_, 
                                            sort=False)]
        data = pd.concat([rest, scaled], axis=1)
        data.to_csv(file_path.replace(origin_directory_path, output_directory_path), index=False)


def apply_normalizer(input_directory_path : str,
                     parallel: bool = True,
                     max_workers: int = 10,
                     maxtasksperchild: int = 1,
                     use_tqdm: bool = True):

    from src.utils.serialized_parallel import process
    
    with open(os.path.join(input_directory_path, "info.json"), "r") as file:
        train_val_test_file_paths = json.load(file)

    args_list = [{
        "train_val_test_file_path": train_val_test_file_path,
        "output_directory_path": os.path.join(input_directory_path, 
                                              str(train_val_test_file_path['index'])),
    } for train_val_test_file_path in train_val_test_file_paths]

    process(
        worker_function=apply_normalizer_one_file,
        worker_params_list=args_list,
        parallel=parallel,
        max_workers=max_workers,
        maxtasksperchild=maxtasksperchild,
        use_tqdm=use_tqdm,
    )

/home/mojtaba.kananisarche/Zh

In [67]:
info, a = apply_normalizer(input_directory_path  = "/work/long_lab/Mojtaba/data/UTA/1.3.3-augmented_embedded_preprocessed_normalized",
                        parallel = True,
                        max_workers = 1,
                        maxtasksperchild = 1,
                        use_tqdm = True)

In [72]:
a[0]['output_directory_path']

'/work/long_lab/Mojtaba/data/UTA/1.3.3-augmented_embedded_preprocessed_normalized/0'

In [73]:
%cd '/home/mojtaba.kananisarche/Zh'
from typing import List, Optional, Tuple
from src.utils.file_folder import create_folders
import os
import json
import pickle
import pandas as pd

def apply_normalizer_one_file(
    train_val_test_file_path : str,
    output_directory_path: str):

    index = train_val_test_file_path['index']
    all_splits_paths = (train_val_test_file_path['paths']['test'] + 
                        train_val_test_file_path['paths']['val'] + 
                        train_val_test_file_path['paths']['train'])
    
    origin_directory_path = os.path.commonpath(all_splits_paths)
    origin_directory_subfolders_path = list(set([os.path.dirname(file_path) for file_path in all_splits_paths]))    
    output_directory_subfolders_path = [folder_path.replace(origin_directory_path, output_directory_path) 
                                        for folder_path in origin_directory_subfolders_path]

    create_folders(output_directory_subfolders_path)

    with open(os.path.join(output_directory_path, f"{index}_normalizer.pkl"), "rb") as file:
        scaler = pickle.load(file)

    for file_path in all_splits_paths:
        data = pd.read_csv(file_path)
        scaled = pd.DataFrame(scaler.transform(data[scaler.feature_names_in_]), 
                              columns = scaler.feature_names_in_)
        rest = data[data.columns.difference(scaler.feature_names_in_, 
                                            sort=False)]
        data = pd.concat([rest, scaled], axis=1)
        data.to_csv(file_path.replace(origin_directory_path, output_directory_path), index=False)

/home/mojtaba.kananisarche/Zh

In [62]:
data, scaler = apply_normalizer_one_file(info[0], "/work/long_lab/Mojtaba/data/UTA/1.3.3-augmented_embedded_preprocessed_normalized/0", [])

In [60]:
data

,file_name,type,frame,fold,subject_id,target,f_0,f_1,f_2,f_3,...,f_118,f_119,f_120,f_121,f_122,f_123,f_124,f_125,f_126,f_127
0,1_01_0_30fps_brightness_alpha0.8_beta-10.csv,brightness,0,1,1,2.0,0.651858,0.196883,-0.031487,-0.171349,...,1.033221,-3.132489,1.022311,0.080711,0.430494,0.438742,0.217288,0.495047,-1.631415,-0.018838
1,1_01_0_30fps_brightness_alpha0.8_beta-10.csv,brightness,1,1,1,2.0,0.580197,0.139444,0.298224,-0.054409,...,0.840605,-3.309029,1.062378,0.226824,0.460953,0.149024,0.300996,0.350112,-1.971213,-0.056789
2,1_01_0_30fps_brightness_alpha0.8_beta-10.csv,brightness,2,1,1,2.0,0.254253,-0.308095,0.616605,-0.323146,...,1.103263,-3.326557,0.308114,-0.672422,0.352317,0.550404,0.308142,0.343623,-1.522235,-0.119733
3,1_01_0_30fps_brightness_alpha0.8_beta-10.csv,brightness,3,1,1,2.0,0.219578,0.110725,0.136201,0.687709,...,0.931660,-3.607018,0.096760,-0.961084,1.054902,0.892432,-0.394191,1.460917,-0.774681,0.280143
4,1_01_0_30fps_brightness_alpha0.8_beta-10.csv,brightness,4,1,1,2.0,1.065645,0.653995,0.882867,0.091766,...,1.133615,-3.852420,-0.637471,-0.089159,0.295460,-0.056193,-0.052212,0.858465,0.465300,0.566165
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18065,1_01_0_30fps_brightness_alpha0.8_beta-10.csv,brightness,18065,1,1,2.0,0.663416,0.624079,0.308421,0.286291,...,1.479158,-3.416705,1.467057,0.759007,0.747267,0.041386,0.698100,-0.003572,-2.109360,0.618001
18066,1_01_0_30fps_brightness_alpha0.8_beta-10.csv,brightness,18066,1,1,2.0,0.508535,0.581001,0.260834,0.170476,...,1.534024,-3.360363,1.306788,0.567754,0.930020,-0.110515,0.556204,0.100262,-2.128299,0.610596
18067,1_01_0_30fps_brightness_alpha0.8_beta-10.csv,brightness,18067,1,1,2.0,0.602158,0.594164,0.367339,0.195213,...,1.521183,-3.422966,1.371897,0.663974,0.850827,-0.102467,0.723621,0.121894,-2.117158,0.530065
18068,1_01_0_30fps_brightness_alpha0.8_beta-10.csv,brightness,18068,1,1,2.0,0.659949,0.732973,0.343545,0.147987,...,1.586556,-3.464283,1.437006,0.734061,0.727976,-0.087378,0.708308,0.000755,-2.039172,0.610596
18069,1_01_0_30fps_brightness_alpha0.8_beta-10.csv,brightness,18069,1,1,2.0,0.709650,0.752119,0.171325,0.026550,...,1.562041,-3.304020,1.386922,0.776825,0.839659,-0.107497,0.656246,0.010489,-2.129413,0.632811

In [35]:
data[scaler.feature_names_in_]

,f_0,f_1,f_2,f_3,f_4,f_5,f_6,f_7,f_8,f_9,...,f_118,f_119,f_120,f_121,f_122,f_123,f_124,f_125,f_126,f_127
0,0.866,0.053,-0.059,-0.064,0.631,1.228,-0.296,-0.825,0.806,1.126,...,0.692,-2.193,1.339,-0.025,1.362,-0.253,-0.255,0.339,-1.202,-0.188
1,0.804,0.005,0.232,0.040,0.599,1.208,-0.165,-0.899,0.828,0.955,...,0.527,-2.334,1.379,0.098,1.392,-0.541,-0.173,0.205,-1.507,-0.229
2,0.522,-0.369,0.513,-0.199,0.064,1.512,-0.385,-0.651,0.479,1.336,...,0.752,-2.348,0.626,-0.659,1.285,-0.142,-0.166,0.199,-1.104,-0.297
3,0.492,-0.019,0.089,0.700,0.093,1.816,0.252,-1.203,-0.503,1.150,...,0.605,-2.572,0.415,-0.902,1.977,0.198,-0.854,1.232,-0.433,0.135
4,1.224,0.435,0.748,0.170,0.636,1.586,0.542,-1.223,-0.970,1.749,...,0.778,-2.768,-0.318,-0.168,1.229,-0.745,-0.519,0.675,0.680,0.444
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18065,0.876,0.410,0.241,0.343,1.879,1.066,0.437,-1.183,0.727,0.083,...,1.074,-2.420,1.783,0.546,1.674,-0.648,0.216,-0.122,-1.631,0.500
18066,0.742,0.374,0.199,0.240,1.682,1.115,0.257,-1.293,0.725,-0.020,...,1.121,-2.375,1.623,0.385,1.854,-0.799,0.077,-0.026,-1.648,0.492
18067,0.823,0.385,0.293,0.262,1.739,1.058,0.512,-1.299,0.531,0.038,...,1.110,-2.425,1.688,0.466,1.776,-0.791,0.241,-0.006,-1.638,0.405
18068,0.873,0.501,0.272,0.220,1.812,1.091,0.346,-1.290,0.713,0.106,...,1.166,-2.458,1.753,0.525,1.655,-0.776,0.226,-0.118,-1.568,0.492
18069,0.916,0.517,0.120,0.112,1.727,1.104,0.266,-1.400,0.731,0.180,...,1.145,-2.330,1.703,0.561,1.765,-0.796,0.175,-0.109,-1.649,0.516

In [ ]:
pd.concat([data[data.columns.difference(scaler.feature_names_in_, sort=False)], 
           data[scaler.feature_names_in_]], axis=1)

,file_name,type,frame,fold,subject_id,target,f_0,f_1,f_2,f_3,...,f_118,f_119,f_120,f_121,f_122,f_123,f_124,f_125,f_126,f_127
0,1_01_0_30fps_brightness_alpha0.8_beta-10.csv,brightness,0,1,1,2.0,0.866,0.053,-0.059,-0.064,...,0.692,-2.193,1.339,-0.025,1.362,-0.253,-0.255,0.339,-1.202,-0.188
1,1_01_0_30fps_brightness_alpha0.8_beta-10.csv,brightness,1,1,1,2.0,0.804,0.005,0.232,0.040,...,0.527,-2.334,1.379,0.098,1.392,-0.541,-0.173,0.205,-1.507,-0.229
2,1_01_0_30fps_brightness_alpha0.8_beta-10.csv,brightness,2,1,1,2.0,0.522,-0.369,0.513,-0.199,...,0.752,-2.348,0.626,-0.659,1.285,-0.142,-0.166,0.199,-1.104,-0.297
3,1_01_0_30fps_brightness_alpha0.8_beta-10.csv,brightness,3,1,1,2.0,0.492,-0.019,0.089,0.700,...,0.605,-2.572,0.415,-0.902,1.977,0.198,-0.854,1.232,-0.433,0.135
4,1_01_0_30fps_brightness_alpha0.8_beta-10.csv,brightness,4,1,1,2.0,1.224,0.435,0.748,0.170,...,0.778,-2.768,-0.318,-0.168,1.229,-0.745,-0.519,0.675,0.680,0.444
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18065,1_01_0_30fps_brightness_alpha0.8_beta-10.csv,brightness,18065,1,1,2.0,0.876,0.410,0.241,0.343,...,1.074,-2.420,1.783,0.546,1.674,-0.648,0.216,-0.122,-1.631,0.500
18066,1_01_0_30fps_brightness_alpha0.8_beta-10.csv,brightness,18066,1,1,2.0,0.742,0.374,0.199,0.240,...,1.121,-2.375,1.623,0.385,1.854,-0.799,0.077,-0.026,-1.648,0.492
18067,1_01_0_30fps_brightness_alpha0.8_beta-10.csv,brightness,18067,1,1,2.0,0.823,0.385,0.293,0.262,...,1.110,-2.425,1.688,0.466,1.776,-0.791,0.241,-0.006,-1.638,0.405
18068,1_01_0_30fps_brightness_alpha0.8_beta-10.csv,brightness,18068,1,1,2.0,0.873,0.501,0.272,0.220,...,1.166,-2.458,1.753,0.525,1.655,-0.776,0.226,-0.118,-1.568,0.492
18069,1_01_0_30fps_brightness_alpha0.8_beta-10.csv,brightness,18069,1,1,2.0,0.916,0.517,0.120,0.112,...,1.145,-2.330,1.703,0.561,1.765,-0.796,0.175,-0.109,-1.649,0.516

In [55]:
data[data.columns.difference(scaler.feature_names_in_, sort=False)]

,file_name,type,frame,fold,subject_id,target
0,1_01_0_30fps_brightness_alpha0.8_beta-10.csv,brightness,0,1,1,2.0
1,1_01_0_30fps_brightness_alpha0.8_beta-10.csv,brightness,1,1,1,2.0
2,1_01_0_30fps_brightness_alpha0.8_beta-10.csv,brightness,2,1,1,2.0
3,1_01_0_30fps_brightness_alpha0.8_beta-10.csv,brightness,3,1,1,2.0
4,1_01_0_30fps_brightness_alpha0.8_beta-10.csv,brightness,4,1,1,2.0
...,...,...,...,...,...,...
18065,1_01_0_30fps_brightness_alpha0.8_beta-10.csv,brightness,18065,1,1,2.0
18066,1_01_0_30fps_brightness_alpha0.8_beta-10.csv,brightness,18066,1,1,2.0
18067,1_01_0_30fps_brightness_alpha0.8_beta-10.csv,brightness,18067,1,1,2.0
18068,1_01_0_30fps_brightness_alpha0.8_beta-10.csv,brightness,18068,1,1,2.0
18069,1_01_0_30fps_brightness_alpha0.8_beta-10.csv,brightness,18069,1,1,2.0

In [47]:
data

,file_name,type,frame,fold,subject_id,target,f_0,f_1,f_2,f_3,...,f_118,f_119,f_120,f_121,f_122,f_123,f_124,f_125,f_126,f_127
0,1_01_0_30fps_brightness_alpha0.8_beta-10.csv,brightness,0,1,1,2.0,0.866,0.053,-0.059,-0.064,...,0.692,-2.193,1.339,-0.025,1.362,-0.253,-0.255,0.339,-1.202,-0.188
1,1_01_0_30fps_brightness_alpha0.8_beta-10.csv,brightness,1,1,1,2.0,0.804,0.005,0.232,0.040,...,0.527,-2.334,1.379,0.098,1.392,-0.541,-0.173,0.205,-1.507,-0.229
2,1_01_0_30fps_brightness_alpha0.8_beta-10.csv,brightness,2,1,1,2.0,0.522,-0.369,0.513,-0.199,...,0.752,-2.348,0.626,-0.659,1.285,-0.142,-0.166,0.199,-1.104,-0.297
3,1_01_0_30fps_brightness_alpha0.8_beta-10.csv,brightness,3,1,1,2.0,0.492,-0.019,0.089,0.700,...,0.605,-2.572,0.415,-0.902,1.977,0.198,-0.854,1.232,-0.433,0.135
4,1_01_0_30fps_brightness_alpha0.8_beta-10.csv,brightness,4,1,1,2.0,1.224,0.435,0.748,0.170,...,0.778,-2.768,-0.318,-0.168,1.229,-0.745,-0.519,0.675,0.680,0.444
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18065,1_01_0_30fps_brightness_alpha0.8_beta-10.csv,brightness,18065,1,1,2.0,0.876,0.410,0.241,0.343,...,1.074,-2.420,1.783,0.546,1.674,-0.648,0.216,-0.122,-1.631,0.500
18066,1_01_0_30fps_brightness_alpha0.8_beta-10.csv,brightness,18066,1,1,2.0,0.742,0.374,0.199,0.240,...,1.121,-2.375,1.623,0.385,1.854,-0.799,0.077,-0.026,-1.648,0.492
18067,1_01_0_30fps_brightness_alpha0.8_beta-10.csv,brightness,18067,1,1,2.0,0.823,0.385,0.293,0.262,...,1.110,-2.425,1.688,0.466,1.776,-0.791,0.241,-0.006,-1.638,0.405
18068,1_01_0_30fps_brightness_alpha0.8_beta-10.csv,brightness,18068,1,1,2.0,0.873,0.501,0.272,0.220,...,1.166,-2.458,1.753,0.525,1.655,-0.776,0.226,-0.118,-1.568,0.492
18069,1_01_0_30fps_brightness_alpha0.8_beta-10.csv,brightness,18069,1,1,2.0,0.916,0.517,0.120,0.112,...,1.145,-2.330,1.703,0.561,1.765,-0.796,0.175,-0.109,-1.649,0.516

In [ ]:
info = apply_normalizer(input_directory_path  = "/work/long_lab/Mojtaba/data/UTA/1.3.3-augmented_embedded_preprocessed_normalized",
                        feature_columns = [],
                        parallel = True,
                        max_workers = 1,
                        maxtasksperchild = 1,
                        use_tqdm = True)

In [18]:
os.path.commonprefix(info[0]['paths']['test'] + info[0]['paths']['val'] + info[0]['paths']['train'])

'/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/'

In [17]:
info[0]['paths']['test'] + info[0]['paths']['val'] + info[0]['paths']['train']

['/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_01_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_01_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_01_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/1_01_0_30fps_contrast_alpha0.7_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/1_01_5_30fps_contrast_alpha0.7_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/1_01_10_30fps_contrast_alpha0.7_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/1_01_0_30fps_flip_flipcode1_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/1_01_10_30fps_flip_flipcode1_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/1_01_5_30fps_flip_flipcode1_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/1_01_0_30fps_rotate_angle-5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/1_01_10_30fps_rotate_angle-5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/1_01_5_30fps_rotate_angle-5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/1_01_10_30fps_brightness_alpha1.2_beta10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/1_01_0_30fps_brightness_alpha1.2_beta10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/1_01_5_30fps_brightness_alpha1.2_beta10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/1_01_0_30fps_grayscale_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/1_01_5_30fps_grayscale_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/1_01_10_30fps_grayscale_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/1_01_0_30fps_rotate_angle5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/1_01_5_30fps_rotate_angle5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/1_01_10_30fps_rotate_angle5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/1_01_0_30fps_cropped_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/1_01_10_30fps_cropped_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/1_01_5_30fps_cropped_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/1_01_0_30fps_contrast_alpha1.5_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/1_01_10_30fps_contrast_alpha1.5_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/1_01_5_30fps_contrast_alpha1.5_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_10_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_10_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_10_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/1_10_0_30fps_contrast_alpha0.7_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/1_10_10_30fps_contrast_alpha0.7_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/1_10_5_30fps_contrast_alpha0.7_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/1_10_10_30fps_flip_flipcode1_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/1_10_5_30fps_flip_flipcode1_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/1_10_0_30fps_flip_flipcode1_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/1_10_10_30fps_rotate_angle-5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/1_10_5_30fps_rotate_angle-5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/1_10_0_30fps_rotate_angle-5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/1_10_10_30fps_brightness_alpha1.2_beta10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/1_10_5_30fps_brightness_alpha1.2_beta10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/1_10_0_30fps_brightness_alpha1.2_beta10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/1_10_10_30fps_grayscale_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/1_10_5_30fps_grayscale_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/1_10_0_30fps_grayscale_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/1_10_10_30fps_rotate_angle5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/1_10_5_30fps_rotate_angle5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/1_10_0_30fps_rotate_angle5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/1_10_5_30fps_cropped_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/1_10_0_30fps_cropped_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/1_10_10_30fps_cropped_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/1_10_10_30fps_contrast_alpha1.5_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/1_10_5_30fps_contrast_alpha1.5_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/1_10_0_30fps_contrast_alpha1.5_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_11_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_11_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_11_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/1_11_5_30fps_contrast_alpha0.7_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/1_11_10_30fps_contrast_alpha0.7_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/1_11_0_30fps_contrast_alpha0.7_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/1_11_5_30fps_flip_flipcode1_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/1_11_10_30fps_flip_flipcode1_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/1_11_0_30fps_flip_flipcode1_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/1_11_5_30fps_rotate_angle-5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/1_11_10_30fps_rotate_angle-5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/1_11_0_30fps_rotate_angle-5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/1_11_0_30fps_brightness_alpha1.2_beta10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/1_11_5_30fps_brightness_alpha1.2_beta10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/1_11_10_30fps_brightness_alpha1.2_beta10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/1_11_5_30fps_grayscale_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/1_11_10_30fps_grayscale_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/1_11_0_30fps_grayscale_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/1_11_5_30fps_rotate_angle5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/1_11_10_30fps_rotate_angle5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/1_11_0_30fps_rotate_angle5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/1_11_5_30fps_cropped_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/1_11_10_30fps_cropped_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/1_11_0_30fps_cropped_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/1_11_0_30fps_contrast_alpha1.5_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/1_11_5_30fps_contrast_alpha1.5_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/1_11_10_30fps_contrast_alpha1.5_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_12_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_12_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_12_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/1_12_0_30fps_contrast_alpha0.7_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/1_12_10_30fps_contrast_alpha0.7_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/1_12_5_30fps_contrast_alpha0.7_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/1_12_0_30fps_flip_flipcode1_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/1_12_10_30fps_flip_flipcode1_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/1_12_5_30fps_flip_flipcode1_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/1_12_10_30fps_rotate_angle-5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/1_12_5_30fps_rotate_angle-5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/1_12_0_30fps_rotate_angle-5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/1_12_0_30fps_brightness_alpha1.2_beta10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/1_12_10_30fps_brightness_alpha1.2_beta10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/1_12_5_30fps_brightness_alpha1.2_beta10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/1_12_0_30fps_grayscale_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/1_12_10_30fps_grayscale_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/1_12_5_30fps_grayscale_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/1_12_0_30fps_rotate_angle5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/1_12_10_30fps_rotate_angle5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/1_12_5_30fps_rotate_angle5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/1_12_0_30fps_cropped_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/1_12_10_30fps_cropped_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/1_12_5_30fps_cropped_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/1_12_0_30fps_contrast_alpha1.5_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/1_12_10_30fps_contrast_alpha1.5_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/1_12_5_30fps_contrast_alpha1.5_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_02_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_02_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_02_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/1_02_0_30fps_contrast_alpha0.7_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/1_02_10_30fps_contrast_alpha0.7_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/1_02_5_30fps_contrast_alpha0.7_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/1_02_5_30fps_flip_flipcode1_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/1_02_0_30fps_flip_flipcode1_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/1_02_10_30fps_flip_flipcode1_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/1_02_0_30fps_rotate_angle-5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/1_02_10_30fps_rotate_angle-5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/1_02_5_30fps_rotate_angle-5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/1_02_5_30fps_brightness_alpha1.2_beta10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/1_02_0_30fps_brightness_alpha1.2_beta10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/1_02_10_30fps_brightness_alpha1.2_beta10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/1_02_0_30fps_grayscale_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/1_02_10_30fps_grayscale_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/1_02_5_30fps_grayscale_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/1_02_5_30fps_rotate_angle5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/1_02_0_30fps_rotate_angle5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/1_02_10_30fps_rotate_angle5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/1_02_5_30fps_cropped_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/1_02_0_30fps_cropped_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/1_02_10_30fps_cropped_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/1_02_5_30fps_contrast_alpha1.5_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/1_02_0_30fps_contrast_alpha1.5_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/1_02_10_30fps_contrast_alpha1.5_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_03_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_03_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_03_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/1_03_5_30fps_contrast_alpha0.7_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/1_03_10_30fps_contrast_alpha0.7_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/1_03_0_30fps_contrast_alpha0.7_beta0_preprocessed.csv',

In [1]:
import numpy as np
import pandas as pd
from typing import List, Optional, Tuple
from keras.src.utils import pad_sequences

def reshape_data_rnn(
    df: pd.DataFrame,
    feature_columns: List[str],
    slice_size: int,
    step_size: Optional[int],
    groupby_column: str = "file_name",
    sortby_column: str = "frame",
    target_column: str = "target",
    discard_threshold_ratio: float = 0.6,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Reshape data for RNN input by grouping, slicing, and padding sequences.

    Args:
        df (pd.DataFrame)              : Input dataframe.
        feature_columns (List[str])    : List of feature column names.
        slice_size (int)               : Maximum number of slices in each chunk.
        step_size (int)                : Step size for moving to the next chunk.
        groupby_column (str)           : Column to group by (e.g., video or file name).
        sortby_column (str)            : Column to sort within each group (e.g., frame index).
        target_column (str)            : Column containing target labels.
        discard_threshold_ratio (float): Last slice in each video will be discarded if the number of its frames is less than
                                         discard_threshold_ratio*max_slice and will be post padded with zero and kept otherwise.
    Returns:
        Tuple[np.ndarray, np.ndarray]: Feature sequences (X) and corresponding labels (y).
    """
    step_size = step_size or slice_size
    X, y, g = [], [], []

    for group_identifier, group in df.groupby(groupby_column):
        # Sort by the specified column to maintain temporal order
        group = group.sort_values(by=sortby_column, ascending=True)

        y_group = group[target_column].unique()
        assert (
            len(y_group) == 1
        ), f"Expected one unique target value, but found {len(y_group)}"
        y_group = y_group[0]

        return group, feature_columns

        # Extract features as a list of lists
        slices = group[feature_columns].values.tolist()

        # Create chunks with the specified step size
        for start_idx in range(0, len(slices) - slice_size + 1, step_size):
            chunk = slices[start_idx : start_idx + slice_size]
            # print(chunk)
            X.append(chunk)
            y.append(y_group)
            g.append(group_identifier)

        discard_threshold_frame = int(discard_threshold_ratio * slice_size)
        if len(slices) - (start_idx + slice_size) > discard_threshold_frame:
            chunk = slices[start_idx + slice_size : len(slices)]
            X.append(chunk)
            y.append(y_group)
            g.append(group_identifier)

    # Pad sequences to ensure uniform length
    X_padded = pad_sequences(X, maxlen=slice_size, padding="post", dtype="float32")

    return np.array(X_padded), np.array(y), np.array(g)

2025-04-23 07:06:04.723261: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [2]:
%cd '/home/mojtaba.kananisarche/Zh'
from src.utils.load_data import load_data

path_to_data = "/work/long_lab/Mojtaba/data/UTA/1.3.3-preprocessed_merged"
preprocessed_data = load_data(
    input_path=path_to_data,
    # file_names=["facenet_preprocessed_alternativemapping.csv"],
    file_names=["facenet_preprocessed_alternativemapping_croppedonly.csv"],
    nrows=1000,
)
columns_to_drop = [
    "file_name",
    "file_name_1",
    "type",
    "frame",
    "fold",
    "subject_id",
]
groupby_column, sortby_column, target_column = "file_name", "frame", "target"
columns_to_drop_1 = [
    column_name
    for column_name in columns_to_drop
    if column_name not in [groupby_column, sortby_column, target_column]
]
preprocessed_data = preprocessed_data.drop(columns=columns_to_drop_1)

feature_columns = [
    column_name
    for column_name in preprocessed_data.columns
    if column_name not in columns_to_drop + [target_column]
]

2025-04-23 07:06:36,527 - INFO - Concatenated file: facenet_preprocessed_alternativemapping_croppedonly.csv, current data shape: (999, 135)

/home/mojtaba.kananisarche/Zh

In [3]:
preprocessed_data

,file_name,frame,target,f_0,f_1,f_2,f_3,f_4,f_5,f_6,...,f_118,f_119,f_120,f_121,f_122,f_123,f_124,f_125,f_126,f_127
0,1_04_0_30fps_cropped.csv,1,2.0,0.478,-0.379,-1.477,0.302,0.154,1.059,-1.415,...,-0.203,-1.138,2.229,-0.254,0.832,-0.449,-1.163,0.223,0.197,-1.463
1,1_04_0_30fps_cropped.csv,2,2.0,0.544,-0.406,-1.544,0.239,0.127,1.061,-1.398,...,-0.206,-1.177,2.155,-0.115,0.867,-0.517,-1.227,0.294,0.128,-1.510
2,1_04_0_30fps_cropped.csv,3,2.0,0.692,-0.342,-1.480,0.186,0.013,1.143,-1.368,...,-0.195,-1.259,2.100,-0.177,0.983,-0.672,-1.287,0.256,0.116,-1.514
3,1_04_0_30fps_cropped.csv,4,2.0,0.674,-0.349,-1.516,0.165,0.024,1.116,-1.326,...,-0.155,-1.278,2.089,-0.149,0.973,-0.635,-1.356,0.278,0.114,-1.484
4,1_04_0_30fps_cropped.csv,5,2.0,0.713,-0.299,-1.586,0.202,0.050,1.002,-1.356,...,-0.245,-1.188,2.139,-0.079,0.900,-0.525,-1.336,0.353,0.150,-1.367
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,1_04_0_30fps_cropped.csv,995,2.0,0.176,-0.087,-0.899,0.611,-0.876,0.808,-1.663,...,-0.809,-0.271,1.886,-0.506,0.760,-0.502,-1.625,1.090,0.249,-1.484
995,1_04_0_30fps_cropped.csv,996,2.0,0.021,-0.404,-0.966,0.555,-0.818,0.817,-1.712,...,-0.791,-0.449,1.652,-0.548,0.922,-0.366,-1.656,1.046,0.387,-1.499
996,1_04_0_30fps_cropped.csv,997,2.0,-0.195,-0.463,-0.912,0.540,-0.789,0.675,-1.642,...,-0.697,-0.564,1.858,-0.500,0.886,-0.525,-1.798,0.950,0.357,-1.364
997,1_04_0_30fps_cropped.csv,998,2.0,-0.273,-0.354,-1.095,0.590,-0.723,0.687,-1.702,...,-0.746,-0.653,1.748,-0.406,0.845,-0.602,-1.719,1.060,0.496,-1.376
998,1_04_0_30fps_cropped.csv,999,2.0,0.062,-0.365,-1.035,0.581,-0.672,0.946,-1.705,...,-0.633,-0.735,1.649,-0.367,1.043,-0.497,-1.566,0.881,0.613,-1.411

In [4]:
g, f = reshape_data_rnn(
    df=preprocessed_data,
    feature_columns=feature_columns,
    slice_size=100,
    step_size=100,
    discard_threshold_ratio=0.7,
    groupby_column=groupby_column,
    sortby_column=sortby_column,
    target_column=target_column,
)

In [5]:
g

,file_name,frame,target,f_0,f_1,f_2,f_3,f_4,f_5,f_6,...,f_118,f_119,f_120,f_121,f_122,f_123,f_124,f_125,f_126,f_127
0,1_04_0_30fps_cropped.csv,1,2.0,0.478,-0.379,-1.477,0.302,0.154,1.059,-1.415,...,-0.203,-1.138,2.229,-0.254,0.832,-0.449,-1.163,0.223,0.197,-1.463
1,1_04_0_30fps_cropped.csv,2,2.0,0.544,-0.406,-1.544,0.239,0.127,1.061,-1.398,...,-0.206,-1.177,2.155,-0.115,0.867,-0.517,-1.227,0.294,0.128,-1.510
2,1_04_0_30fps_cropped.csv,3,2.0,0.692,-0.342,-1.480,0.186,0.013,1.143,-1.368,...,-0.195,-1.259,2.100,-0.177,0.983,-0.672,-1.287,0.256,0.116,-1.514
3,1_04_0_30fps_cropped.csv,4,2.0,0.674,-0.349,-1.516,0.165,0.024,1.116,-1.326,...,-0.155,-1.278,2.089,-0.149,0.973,-0.635,-1.356,0.278,0.114,-1.484
4,1_04_0_30fps_cropped.csv,5,2.0,0.713,-0.299,-1.586,0.202,0.050,1.002,-1.356,...,-0.245,-1.188,2.139,-0.079,0.900,-0.525,-1.336,0.353,0.150,-1.367
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,1_04_0_30fps_cropped.csv,995,2.0,0.176,-0.087,-0.899,0.611,-0.876,0.808,-1.663,...,-0.809,-0.271,1.886,-0.506,0.760,-0.502,-1.625,1.090,0.249,-1.484
995,1_04_0_30fps_cropped.csv,996,2.0,0.021,-0.404,-0.966,0.555,-0.818,0.817,-1.712,...,-0.791,-0.449,1.652,-0.548,0.922,-0.366,-1.656,1.046,0.387,-1.499
996,1_04_0_30fps_cropped.csv,997,2.0,-0.195,-0.463,-0.912,0.540,-0.789,0.675,-1.642,...,-0.697,-0.564,1.858,-0.500,0.886,-0.525,-1.798,0.950,0.357,-1.364
997,1_04_0_30fps_cropped.csv,998,2.0,-0.273,-0.354,-1.095,0.590,-0.723,0.687,-1.702,...,-0.746,-0.653,1.748,-0.406,0.845,-0.602,-1.719,1.060,0.496,-1.376
998,1_04_0_30fps_cropped.csv,999,2.0,0.062,-0.365,-1.035,0.581,-0.672,0.946,-1.705,...,-0.633,-0.735,1.649,-0.367,1.043,-0.497,-1.566,0.881,0.613,-1.411

In [6]:
f

['f_0',
 'f_1',
 'f_2',
 'f_3',
 'f_4',
 'f_5',
 'f_6',
 'f_7',
 'f_8',
 'f_9',
 'f_10',
 'f_11',
 'f_12',
 'f_13',
 'f_14',
 'f_15',
 'f_16',
 'f_17',
 'f_18',
 'f_19',
 'f_20',
 'f_21',
 'f_22',
 'f_23',
 'f_24',
 'f_25',
 'f_26',
 'f_27',
 'f_28',
 'f_29',
 'f_30',
 'f_31',
 'f_32',
 'f_33',
 'f_34',
 'f_35',
 'f_36',
 'f_37',
 'f_38',
 'f_39',
 'f_40',
 'f_41',
 'f_42',
 'f_43',
 'f_44',
 'f_45',
 'f_46',
 'f_47',
 'f_48',
 'f_49',
 'f_50',
 'f_51',
 'f_52',
 'f_53',
 'f_54',
 'f_55',
 'f_56',
 'f_57',
 'f_58',
 'f_59',
 'f_60',
 'f_61',
 'f_62',
 'f_63',
 'f_64',
 'f_65',
 'f_66',
 'f_67',
 'f_68',
 'f_69',
 'f_70',
 'f_71',
 'f_72',
 'f_73',
 'f_74',
 'f_75',
 'f_76',
 'f_77',
 'f_78',
 'f_79',
 'f_80',
 'f_81',
 'f_82',
 'f_83',
 'f_84',
 'f_85',
 'f_86',
 'f_87',
 'f_88',
 'f_89',
 'f_90',
 'f_91',
 'f_92',
 'f_93',
 'f_94',
 'f_95',
 'f_96',
 'f_97',
 'f_98',
 'f_99',
 'f_100',
 'f_101',
 'f_102',
 'f_103',
 'f_104',
 'f_105',
 'f_106',
 'f_107',
 'f_108',
 'f_109',
 'f_110',
 'f_111',
 'f_112',
 'f_113',
 'f_114',
 'f_115',
 'f_116',
 'f_117',
 'f_118',
 'f_119',
 'f_120',
 'f_121',
 'f_122',
 'f_123',
 'f_124',
 'f_125',
 'f_126',
 'f_127']

In [1]:
%cd '/home/mojtaba.kananisarche/Zh'

from src.utils.split_files import _get_train_val_test_file_paths

/home/mojtaba.kananisarche/Zh

In [3]:
p = _get_train_val_test_file_paths(
    input_path = "/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed",
    primary_column_name = "fold"
)

In [43]:
p

[{'index': 0,
  'info': {'test': {'fold': ['1']},
   'val': {'fold': ['2']},
   'train': {'fold': ['3', '4', '5']}},
  'paths': {'test': ['/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_01_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_01_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_01_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/1_01_0_30fps_contrast_alpha0.7_beta0_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/1_01_5_30fps_contrast_alpha0.7_beta0_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/1_01_10_30fps_contrast_alpha0.7_beta0_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/1_01_0_30fps_flip_flipcode1_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/1_01_10_30fps_flip_flipcode1_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/1_01_5_30fps_flip_flipcode1_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/1_01_0_30fps_rotate_angle-5_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/1_01_10_30fps_rotate_angle-5_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/1_01_5_30fps_rotate_angle-5_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/1_01_10_30fps_brightness_alpha1.2_beta10_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/1_01_0_30fps_brightness_alpha1.2_beta10_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/1_01_5_30fps_brightness_alpha1.2_beta10_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/1_01_0_30fps_grayscale_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/1_01_5_30fps_grayscale_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/1_01_10_30fps_grayscale_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/1_01_0_30fps_rotate_angle5_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/1_01_5_30fps_rotate_angle5_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/1_01_10_30fps_rotate_angle5_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/1_01_0_30fps_cropped_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/1_01_10_30fps_cropped_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/1_01_5_30fps_cropped_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/1_01_0_30fps_contrast_alpha1.5_beta0_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/1_01_10_30fps_contrast_alpha1.5_beta0_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/1_01_5_30fps_contrast_alpha1.5_beta0_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_10_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_10_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_10_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/1_10_0_30fps_contrast_alpha0.7_beta0_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/1_10_10_30fps_contrast_alpha0.7_beta0_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/1_10_5_30fps_contrast_alpha0.7_beta0_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/1_10_10_30fps_flip_flipcode1_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/1_10_5_30fps_flip_flipcode1_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/1_10_0_30fps_flip_flipcode1_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/1_10_10_30fps_rotate_angle-5_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/1_10_5_30fps_rotate_angle-5_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/1_10_0_30fps_rotate_angle-5_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/1_10_10_30fps_brightness_alpha1.2_beta10_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/1_10_5_30fps_brightness_alpha1.2_beta10_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/1_10_0_30fps_brightness_alpha1.2_beta10_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/1_10_10_30fps_grayscale_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/1_10_5_30fps_grayscale_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/1_10_0_30fps_grayscale_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/1_10_10_30fps_rotate_angle5_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/1_10_5_30fps_rotate_angle5_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/1_10_0_30fps_rotate_angle5_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/1_10_5_30fps_cropped_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/1_10_0_30fps_cropped_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/1_10_10_30fps_cropped_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/1_10_10_30fps_contrast_alpha1.5_beta0_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/1_10_5_30fps_contrast_alpha1.5_beta0_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/1_10_0_30fps_contrast_alpha1.5_beta0_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_11_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_11_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_11_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/1_11_5_30fps_contrast_alpha0.7_beta0_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/1_11_10_30fps_contrast_alpha0.7_beta0_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/1_11_0_30fps_contrast_alpha0.7_beta0_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/1_11_5_30fps_flip_flipcode1_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/1_11_10_30fps_flip_flipcode1_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/1_11_0_30fps_flip_flipcode1_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/1_11_5_30fps_rotate_angle-5_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/1_11_10_30fps_rotate_angle-5_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/1_11_0_30fps_rotate_angle-5_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/1_11_0_30fps_brightness_alpha1.2_beta10_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/1_11_5_30fps_brightness_alpha1.2_beta10_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/1_11_10_30fps_brightness_alpha1.2_beta10_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/1_11_5_30fps_grayscale_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/1_11_10_30fps_grayscale_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/1_11_0_30fps_grayscale_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/1_11_5_30fps_rotate_angle5_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/1_11_10_30fps_rotate_angle5_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/1_11_0_30fps_rotate_angle5_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/1_11_5_30fps_cropped_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/1_11_10_30fps_cropped_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/1_11_0_30fps_cropped_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/1_11_0_30fps_contrast_alpha1.5_beta0_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/1_11_5_30fps_contrast_alpha1.5_beta0_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/1_11_10_30fps_contrast_alpha1.5_beta0_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_12_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_12_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_12_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/1_12_0_30fps_contrast_alpha0.7_beta0_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/1_12_10_30fps_contrast_alpha0.7_beta0_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/1_12_5_30fps_contrast_alpha0.7_beta0_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/1_12_0_30fps_flip_flipcode1_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/1_12_10_30fps_flip_flipcode1_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/1_12_5_30fps_flip_flipcode1_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/1_12_10_30fps_rotate_angle-5_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/1_12_5_30fps_rotate_angle-5_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/1_12_0_30fps_rotate_angle-5_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/1_12_0_30fps_brightness_alpha1.2_beta10_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/1_12_10_30fps_brightness_alpha1.2_beta10_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/1_12_5_30fps_brightness_alpha1.2_beta10_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/1_12_0_30fps_grayscale_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/1_12_10_30fps_grayscale_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/1_12_5_30fps_grayscale_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/1_12_0_30fps_rotate_angle5_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/1_12_10_30fps_rotate_angle5_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/1_12_5_30fps_rotate_angle5_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/1_12_0_30fps_cropped_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/1_12_10_30fps_cropped_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/1_12_5_30fps_cropped_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/1_12_0_30fps_contrast_alpha1.5_beta0_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/1_12_10_30fps_contrast_alpha1.5_beta0_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/1_12_5_30fps_contrast_alpha1.5_beta0_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_02_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_02_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_02_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/1_02_0_30fps_contrast_alpha0.7_beta0_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/1_02_10_30fps_contrast_alpha0.7_beta0_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/1_02_5_30fps_contrast_alpha0.7_beta0_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/1_02_5_30fps_flip_flipcode1_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/1_02_0_30fps_flip_flipcode1_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/1_02_10_30fps_flip_flipcode1_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/1_02_0_30fps_rotate_angle-5_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/1_02_10_30fps_rotate_angle-5_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/1_02_5_30fps_rotate_angle-5_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/1_02_5_30fps_brightness_alpha1.2_beta10_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/1_02_0_30fps_brightness_alpha1.2_beta10_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/1_02_10_30fps_brightness_alpha1.2_beta10_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/1_02_0_30fps_grayscale_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/1_02_10_30fps_grayscale_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/1_02_5_30fps_grayscale_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/1_02_5_30fps_rotate_angle5_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/1_02_0_30fps_rotate_angle5_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/1_02_10_30fps_rotate_angle5_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/1_02_5_30fps_cropped_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/1_02_0_30fps_cropped_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/1_02_10_30fps_cropped_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/1_02_5_30fps_contrast_alpha1.5_beta0_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/1_02_0_30fps_contrast_alpha1.5_beta0_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/1_02_10_30fps_contrast_alpha1.5_beta0_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_03_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
    '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_03_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',

In [ ]:
from typing import Union, List, Dict, Any
from src.utils.file_folder import create_folders
from src.utils.common import save_obj
import numpy as np
import os


def fit_normalizer_one_file(train_val_test_file_path, output_directory_path,
                            chunk_size, feature_columns):

    import pandas as pd
    from sklearn.preprocessing import StandardScaler
    index = train_val_test_file_path['index']

    output_file_path = os.path.join(output_directory_path,
                                    str(index) + "_normalizer.pkl")

    scaler = StandardScaler()
    for file_path in train_val_test_file_path['paths']['train'][:3]:
        print(f"{index} - {file_path}")
        for chunk in pd.read_csv(file_path, chunksize=chunk_size):
            chunk = chunk[feature_columns]
            scaler.partial_fit(chunk)
    return {'obj': scaler, 'output_path': output_file_path, 'file_type': 'pickle'}

def fit_normalizer(train_val_test_file_paths: List[Dict],
                   output_directory_path: str,
                   chunk_size: 1000,
                   feature_columns: List[str],
                   parallel: bool = True,
                   max_workers: int = 10,
                   maxtasksperchild: int = 1,
                   use_tqdm: bool = True):

    from src.utils.serialized_parallel import process
    
    save_obj(obj=train_val_test_file_paths,
             output_path=os.path.join(output_directory_path, 'info.json'),
             file_type='json')

    create_folders(output_directory_path)

    args_list = [{
        "train_val_test_file_path": train_val_test_file_path,
        "output_directory_path": output_directory_path,
        "chunk_size": chunk_size,
        "feature_columns": feature_columns,
    } for train_val_test_file_path in train_val_test_file_paths]

    process(
        worker_function=fit_normalizer_one_file,
        handler_function=save_obj,
        worker_params_list=args_list,
        parallel=parallel,
        max_workers=max_workers,
        maxtasksperchild=maxtasksperchild,
        use_tqdm=use_tqdm,
    )

In [ ]:
["f_{i}" for i in range(1)]

In [60]:
fit_normalizer(train_val_test_file_paths = p, output_directory_path = "/home/mojtaba.kananisarche/Zh/temp", chunk_size=1000, feature_columns = ['f_1', "f_2"])

  0%|          | 0/20 [00:00<?, ?it/s]

0 - /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_25_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv
0 - /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_25_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv
0 - /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_25_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv

  5%|▌         | 1/20 [00:01<00:31,  1.68s/it]

1 - /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/2_13_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv
1 - /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/2_13_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv
1 - /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/2_13_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv

 10%|█         | 2/20 [00:04<00:41,  2.33s/it]

2 - /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/2_13_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv
2 - /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/2_13_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv
2 - /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/2_13_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv

 15%|█▌        | 3/20 [00:06<00:35,  2.08s/it]

3 - /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/2_13_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv
3 - /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/2_13_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv
3 - /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/2_13_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv

 20%|██        | 4/20 [00:08<00:31,  1.96s/it]

4 - /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_25_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv
4 - /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_25_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv
4 - /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_25_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv

 25%|██▌       | 5/20 [00:09<00:27,  1.85s/it]

5 - /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_01_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv
5 - /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_01_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv
5 - /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_01_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv

 30%|███       | 6/20 [00:11<00:27,  1.95s/it]

6 - /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_01_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv
6 - /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_01_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv
6 - /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_01_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv

 35%|███▌      | 7/20 [00:13<00:24,  1.86s/it]

7 - /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_01_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv
7 - /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_01_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv
7 - /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_01_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv

 40%|████      | 8/20 [00:15<00:21,  1.80s/it]

8 - /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/2_13_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv
8 - /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/2_13_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv
8 - /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/2_13_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv

 45%|████▌     | 9/20 [00:16<00:19,  1.78s/it]

9 - /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_01_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv
9 - /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_01_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv
9 - /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_01_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv

 50%|█████     | 10/20 [00:18<00:17,  1.80s/it]

10 - /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_01_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv
10 - /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_01_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv
10 - /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_01_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv

 55%|█████▌    | 11/20 [00:20<00:15,  1.76s/it]

11 - /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_01_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv
11 - /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_01_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv
11 - /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_01_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv

 60%|██████    | 12/20 [00:22<00:13,  1.73s/it]

12 - /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/2_13_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv
12 - /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/2_13_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv
12 - /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/2_13_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv

 65%|██████▌   | 13/20 [00:23<00:12,  1.74s/it]

13 - /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_01_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv
13 - /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_01_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv
13 - /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_01_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv

 70%|███████   | 14/20 [00:25<00:10,  1.71s/it]

14 - /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_01_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv
14 - /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_01_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv
14 - /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_01_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv

 75%|███████▌  | 15/20 [00:27<00:08,  1.70s/it]

15 - /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_01_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv
15 - /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_01_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv
15 - /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_01_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv

 80%|████████  | 16/20 [00:28<00:07,  1.80s/it]

16 - /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/2_13_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv

ParserError: Error tokenizing data. C error: Calling read(nbytes) on source failed. Try engine='python'.

In [ ]:
def fit_normalizer_one_file(train_val_test_file_path, output_path, chunk_size, feature_columns):
    scaler = StandardScaler()
    for file_path in train_val_test_file_path['paths']['train']:
        print(file_path)
        for chunk in pd.read_csv(file_path, chunksize=chunk_size):
            chunk = chunk[feature_columns]
            scaler.partial_fit(chunk)
    return scaler

In [36]:
c = fit_normalizer_one_file(p[0], '', 1000, ['frame', 'fold'])

/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_25_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv
/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_25_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv
/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_25_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv
/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/3_25_5_30fps_contrast_alpha0.7_beta0_preprocessed.csv
/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/3_25_10_30fps_contrast_alpha0.7_beta0_preprocessed.csv

In [ ]:

def pickle_obj(obj, output_path):
    """
    Save an object to a file using pickle.

    Args:
        obj (Any): The object to be pickled.
        output_path (str): The path where the pickled file will be saved.
    """
    import pickle

    with open(output_path, 'wb') as file:
        pickle.dump(obj, file)