In [3]:
import multiprocessing
import time
from functools import partial

class ParallelProcessor:
    def __init__(self, data, multiplier):
        self.data = data
        self.multiplier = multiplier  # Property that will be used in the method

    def process_item(self, x):
        time.sleep(1)  # Simulate a time-consuming operation
        return (x * self.multiplier)  # Use both the input and the class property

    def process_data(self):
        # Use functools.partial to bind the instance method and class property
        func = partial(self.process_item)
        
        # Create a pool of worker processes
        with multiprocessing.Pool(4) as pool:
            # Map the function to the data in parallel
            results = pool.map(func, self.data)
        
        return results

if __name__ == "__main__":
    data = [1, 2, 3, 4, 5]
    multiplier = 2  # Class property that will be used
    processor = ParallelProcessor(data, multiplier)
    results = processor.process_data()
    print(f"Results: {results}")

Results: [2, 4, 6, 8, 10]

In [3]:
%cd '/home/mojtaba.kananisarche/'

/home/mojtaba.kananisarche

In [4]:
from Zh.src.utils.video import *
import cv2

In [ ]:
path = '/work/long_lab/Mojtaba/augmented/cropped/1_08_0_30fps_cropped.mp4'
cap = cv2.VideoCapture(path)
get_video_info(cap)

(30, 174, 174, 18158)

:

In [6]:
from Zh.src.utils.face_detection.face_detector import *

2025-04-02 04:24:05.194800: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-04-02 04:24:05.203115: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-04-02 04:24:05.233913: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1743589445.287291 2442567 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1743589445.303647 2442567 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1743589445.338599 2442567 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1743589445.338619 2442567 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1743589445.338624 2442567 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1743589445.338628 2442567 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2025-04-02 04:24:05.351805: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [4]:
!pwd

/home/mojtaba.kananisarche/Zh/temp

In [10]:
from Zh.src.utils.face_detection.face_detector import *
from Zh.src.utils.crop.cropper import *
from Zh.src.utils.video import *
import cv2
import os
import mediapipe as mp

In [11]:
detector = FaceDetector(False, False, 1).landmarker

I0000 00:00:1743584268.745807 2183098 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1743584268.755812 2194120 gl_context.cc:369] GL version: 3.2 (OpenGL ES 3.2 Mesa 23.1.4), renderer: llvmpipe (LLVM 17.0.6, 256 bits)
W0000 00:00:1743584268.758815 2183098 face_landmarker_graph.cc:174] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1743584268.780514 2194126 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1743584268.820243 2194139 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

In [12]:
input_folder='/home/mojtaba.kananisarche/Zh/data/UTA/1-raw_30fps'
video_file = os.listdir(input_folder)[1]
file_path = os.path.join(input_folder, video_file)
print(file_path)

/home/mojtaba.kananisarche/Zh/data/UTA/1-raw_30fps/1_04_0_30fps.mp4

In [14]:
cap = cv2.VideoCapture(file_path)
fps, width, height, total_frames = get_video_info(cap)
for i in range(10):
    ret, frame = cap.read()
    mp_image = mp.Image(image_format=mp.ImageFormat.SRGB, data=frame)
    d = detector.detect(mp_image)
    cropped_face = crop_face_from_frame(frame, d, width, height, margin=0.1)
    print(cropped_face)

[[[ 91  93  97]
  [ 91  93  97]
  [ 91  93  97]
  ...
  [ 66  57  55]
  [ 66  57  55]
  [ 65  56  54]]

 [[ 91  93  97]
  [ 91  93  97]
  [ 91  93  97]
  ...
  [ 66  57  55]
  [ 66  57  55]
  [ 64  55  53]]

 [[ 91  93  97]
  [ 91  93  97]
  [ 91  93  97]
  ...
  [ 66  57  55]
  [ 65  56  54]
  [ 64  55  53]]

 ...

 [[253 253 251]
  [254 254 252]
  [254 254 252]
  ...
  [224 224 222]
  [222 222 219]
  [219 220 216]]

 [[253 253 251]
  [254 254 252]
  [254 254 252]
  ...
  [222 222 220]
  [221 221 219]
  [219 220 216]]

 [[253 253 251]
  [254 254 252]
  [254 254 252]
  ...
  [222 222 220]
  [221 221 219]
  [219 219 217]]]
[[[ 91  93  97]
  [ 91  93  97]
  [ 91  93  97]
  ...
  [ 66  57  55]
  [ 66  57  55]
  [ 64  55  53]]

 [[ 91  93  97]
  [ 91  93  97]
  [ 91  93  97]
  ...
  [ 66  57  55]
  [ 66  57  55]
  [ 64  55  53]]

 [[ 92  94  98]
  [ 92  94  98]
  [ 92  94  98]
  ...
  [ 65  56  54]
  [ 64  55  53]
  [ 64  55  53]]

 ...

 [[254 254 252]
  [254 254 252]
  [254 254 252]
  ...
  [226 226 224]
  [225 225 223]
  [223 223 221]]

 [[254 254 252]
  [255 255 253]
  [255 255 253]
  ...
  [225 225 223]
  [224 224 222]
  [222 222 220]]

 [[255 255 253]
  [255 255 253]
  [255 255 253]
  ...
  [224 224 222]
  [222 222 220]
  [221 221 219]]]
[[[ 91  93  97]
  [ 91  93  97]
  [ 91  93  97]
  ...
  [ 66  57  55]
  [ 66  57  55]
  [ 64  55  53]]

 [[ 91  93  97]
  [ 91  93  97]
  [ 91  93  97]
  ...
  [ 66  57  55]
  [ 66  57  55]
  [ 64  55  53]]

 [[ 92  94  98]
  [ 92  94  98]
  [ 92  94  98]
  ...
  [ 65  56  54]
  [ 64  55  53]
  [ 64  55  53]]

 ...

 [[254 254 252]
  [254 254 252]
  [254 254 252]
  ...
  [225 225 223]
  [224 224 222]
  [222 222 220]]

 [[255 255 253]
  [255 255 253]
  [255 255 253]
  ...
  [224 224 222]
  [222 222 220]
  [221 221 219]]

 [[255 255 253]
  [255 255 253]
  [255 255 253]
  ...
  [223 223 221]
  [221 221 219]
  [219 219 217]]]
[[[ 91  93  97]
  [ 91  93  97]
  [ 91  93  97]
  ...
  [ 66  57  55]
  [ 66  57  55]
  [ 66  57  55]]

 [[ 91  93  97]
  [ 91  93  97]
  [ 91  93  97]
  ...
  [ 66  57  55]
  [ 66  57  55]
  [ 66  57  55]]

 [[ 92  94  98]
  [ 92  94  98]
  [ 92  94  98]
  ...
  [ 66  57  55]
  [ 66  57  55]
  [ 64  55  53]]

 ...

 [[255 255 253]
  [255 255 253]
  [255 255 253]
  ...
  [227 227 225]
  [225 225 223]
  [222 222 220]]

 [[255 255 253]
  [255 255 253]
  [255 255 253]
  ...
  [225 225 223]
  [224 224 222]
  [222 222 220]]

 [[255 255 253]
  [255 255 253]
  [255 255 253]
  ...
  [225 225 223]
  [222 222 220]
  [221 221 219]]]
[[[ 91  93  97]
  [ 91  93  97]
  [ 91  93  97]
  ...
  [ 66  57  55]
  [ 66  57  55]
  [ 66  57  55]]

 [[ 91  93  97]
  [ 91  93  97]
  [ 91  93  97]
  ...
  [ 66  57  55]
  [ 66  57  55]
  [ 66  57  55]]

 [[ 92  94  98]
  [ 92  94  98]
  [ 92  94  98]
  ...
  [ 66  57  55]
  [ 66  57  55]
  [ 64  55  53]]

 ...

 [[255 255 253]
  [255 255 253]
  [255 255 253]
  ...
  [227 227 225]
  [225 225 223]
  [222 222 220]]

 [[255 255 253]
  [255 255 253]
  [255 255 253]
  ...
  [225 225 223]
  [224 224 222]
  [222 222 220]]

 [[255 255 253]
  [255 255 253]
  [255 255 253]
  ...
  [225 225 223]
  [222 222 220]
  [221 221 219]]]
[[[ 91  93  97]
  [ 91  93  97]
  [ 91  93  97]
  ...
  [ 66  57  55]
  [ 66  57  55]
  [ 66  57  55]]

 [[ 92  94  98]
  [ 92  94  98]
  [ 92  94  98]
  ...
  [ 66  57  55]
  [ 66  57  55]
  [ 66  57  55]]

 [[ 93  94 101]
  [ 93  94 101]
  [ 93  94 101]
  ...
  [ 66  57  55]
  [ 66  57  55]
  [ 65  56  54]]

 ...

 [[254 254 252]
  [255 255 253]
  [255 255 253]
  ...
  [227 228 225]
  [226 226 224]
  [226 226 224]]

 [[255 255 253]
  [255 255 253]
  [255 255 253]
  ...
  [226 227 223]
  [226 226 224]
  [225 225 223]]

 [[254 254 252]
  [255 255 253]
  [255 255 253]
  ...
  [224 225 221]
  [224 224 222]
  [222 222 220]]]
[[[ 94  95 102]
  [ 93  94 101]
  [ 93  94 101]
  ...
  [ 66  56  56]
  [ 66  57  55]
  [ 66  57  55]]

 [[ 94  95 102]
  [ 93  94 101]
  [ 93  94 101]
  ...
  [ 66  56  56]
  [ 66  57  55]
  [ 66  57  55]]

 [[ 94  96 100]
  [ 94  96 100]
  [ 94  96 100]
  ...
  [ 65  56  54]
  [ 65  56  54]
  [ 65  56  54]]

 ...

 [[255 255 253]
  [255 255 253]
  [255 255 253]
  ...
  [226 228 221]
  [227 229 222]
  [226 228 221]]

 [[255 255 253]
  [255 255 253]
  [255 255 253]
  ...
  [226 228 221]
  [225 227 220]
  [224 226 219]]

 [[255 255 253]
  [255 255 253]
  [255 255 253]
  ...
  [224 226 219]
  [225 227 220]
  [222 224 217]]]
[[[ 94  95 102]
  [ 93  94 101]
  [ 93  94 101]
  ...
  [ 66  56  56]
  [ 66  56  56]
  [ 66  56  56]]

 [[ 94  95 102]
  [ 93  94 101]
  [ 93  94 101]
  ...
  [ 66  56  56]
  [ 66  56  56]
  [ 66  56  56]]

 [[ 94  96 100]
  [ 94  96 100]
  [ 94  96 100]
  ...
  [ 65  56  54]
  [ 65  56  54]
  [ 65  56  54]]

 ...

 [[254 254 252]
  [254 254 252]
  [254 254 252]
  ...
  [226 228 221]
  [224 226 219]
  [224 226 219]]

 [[254 254 252]
  [254 254 252]
  [254 254 252]
  ...
  [222 223 219]
  [221 222 218]
  [221 222 218]]

 [[254 254 252]
  [254 254 252]
  [254 254 252]
  ...
  [219 220 216]
  [219 220 216]
  [218 219 215]]]
[[[ 91  92  99]
  [ 90  91  98]
  [ 90  91  98]
  ...
  [ 62  52  52]
  [ 63  53  53]
  [ 63  53  53]]

 [[ 91  93  97]
  [ 91  93  97]
  [ 91  93  97]
  ...
  [ 62  53  51]
  [ 63  54  52]
  [ 63  54  52]]

 [[ 91  93  97]
  [ 91  93  97]
  [ 91  93  97]
  ...
  [ 62  53  51]
  [ 63  54  52]
  [ 63  54  52]]

 ...

 [[251 251 249]
  [251 251 249]
  [251 251 249]
  ...
  [224 224 222]
  [224 224 222]
  [223 223 221]]

 [[251 251 249]
  [251 251 249]
  [251 251 249]
  ...
  [220 220 218]
  [220 220 218]
  [219 219 217]]

 [[251 251 249]
  [251 251 249]
  [251 251 249]
  ...
  [218 218 216]
  [219 219 217]
  [219 219 217]]]
[[[ 93  95  99]
  [ 93  95  99]
  [ 93  95  99]
  ...
  [ 61  54  49]
  [ 62  54  49]
  [ 62  54  49]]

 [[ 96  98 102]
  [ 96  98 102]
  [ 96  98 102]
  ...
  [ 61  54  49]
  [ 62  54  49]
  [ 62  54  49]]

 [[ 98 100 104]
  [ 98 100 104]
  [ 98 100 104]
  ...
  [ 61  54  49]
  [ 62  54  49]
  [ 62  54  49]]

 ...

 [[251 253 251]
  [251 253 253]
  [251 253 253]
  ...
  [234 235 231]
  [234 235 231]
  [233 234 230]]

 [[252 254 252]
  [252 254 254]
  [252 254 254]
  ...
  [224 225 221]
  [223 224 220]
  [222 223 219]]

 [[252 254 252]
  [252 254 254]
  [252 254 254]
  ...
  [216 217 213]
  [214 215 211]
  [214 215 211]]]

In [2]:
from Zh.src.process.face_video_processor import *

2025-04-02 03:51:22.385566: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-04-02 03:51:22.393411: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-04-02 03:51:22.423780: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1743587482.476808 2335868 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1743587482.493079 2335868 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1743587482.527123 2335868 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1743587482.527140 2335868 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1743587482.527144 2335868 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1743587482.527149 2335868 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2025-04-02 03:51:22.538534: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [3]:
input_folder='/home/mojtaba.kananisarche/Zh/data/UTA/1-raw_30fps'
output_folder='/home/mojtaba.kananisarche/Zh/temp/out'

vp = VideoProcessor(input_folder=input_folder,
                    output_folder=output_folder,
                    use_tqdm=True)

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1743587489.750722 2335868 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1743587489.780285 2339379 gl_context.cc:369] GL version: 3.2 (OpenGL ES 3.2 Mesa 23.1.4), renderer: llvmpipe (LLVM 17.0.6, 256 bits)
W0000 00:00:1743587489.781225 2335868 face_landmarker_graph.cc:174] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
W0000 00:00:1743587489.823174 2339383 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1743587489.865629 2339398 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

In [ ]:
augmentations = {
    "gaussianblur": [
        {"kernel_size": 3},
        {"kernel_size": 5}
    ],
    "brightness": [
        {"alpha": 1.2, "beta": 10},
        {"alpha": 0.8, "beta": -10}
    ],
    "contrast": [
        {"alpha": 1.5, "beta": 0},
        {"alpha": 0.7, "beta": 0}
    ],
    "flip": [
        {"flip_code": 1},  # Horizontal flip
        {"flip_code": 0},  # Vertical flip
        {"flip_code": -1}  # Both horizontal and vertical
    ],
    "grayscale": [{}],  # No parameters needed
    "rotate": [
        {"angle": 15},
        {"angle": -15}
    ]
}
    
vp.process_single_video(
    os.listdir(input_folder)[1],
    0,
    1,
    augmentations,
    True,
    True
)

Processing 1_04_0_30fps.mp4:   0%|          | 0/30 [00:00<?, ?frame/s]

frame = 0.0

Processing 1_04_0_30fps.mp4:  10%|█         | 3/30 [00:00<00:03,  7.15frame/s]

frame = 1.0
frame = 2.0
frame = 3.0

Processing 1_04_0_30fps.mp4:  17%|█▋        | 5/30 [00:00<00:02,  9.61frame/s]

frame = 4.0
frame = 5.0
frame = 6.0

Processing 1_04_0_30fps.mp4:  30%|███       | 9/30 [00:00<00:01, 12.05frame/s]

frame = 7.0
frame = 8.0
frame = 9.0
frame = 10.0

Processing 1_04_0_30fps.mp4:  53%|█████▎    | 16/30 [00:01<00:00, 21.57frame/s]

frame = 11.0
frame = 12.0
frame = 13.0
frame = 14.0
frame = 15.0
frame = 16.0
frame = 17.0

Processing 1_04_0_30fps.mp4:  77%|███████▋  | 23/30 [00:01<00:00, 25.63frame/s]

frame = 18.0
frame = 19.0
frame = 20.0
frame = 21.0
frame = 22.0
frame = 23.0
frame = 24.0

Processing 1_04_0_30fps.mp4: 100%|██████████| 30/30 [00:01<00:00, 18.98frame/s]

frame = 25.0
frame = 26.0
frame = 27.0
frame = 28.0
frame = 29.0
saving

Saving 1_04_0_30fps_cropped.mp4: 100%|██████████| 30/30 [00:00<00:00, 998.20frame/s]

saved /home/mojtaba.kananisarche/Zh/temp/out/cropped/1_04_0_30fps_cropped.mp4

Saving 1_04_0_30fps_gaussian_blur_kernelsize-3.mp4: 100%|██████████| 30/30 [00:00<00:00, 1191.99frame/s]
Saving 1_04_0_30fps_gaussian_blur_kernelsize-5.mp4: 100%|██████████| 30/30 [00:00<00:00, 1210.79frame/s]
Saving 1_04_0_30fps_brightness_alpha-1.2_beta-10.mp4: 100%|██████████| 30/30 [00:00<00:00, 1186.49frame/s]
Saving 1_04_0_30fps_brightness_alpha-0.8_beta--10.mp4: 100%|██████████| 30/30 [00:00<00:00, 1214.39frame/s]
Saving 1_04_0_30fps_contrast_alpha-1.5_beta-0.mp4: 100%|██████████| 30/30 [00:00<00:00, 1115.07frame/s]
Saving 1_04_0_30fps_contrast_alpha-0.7_beta-0.mp4: 100%|██████████| 30/30 [00:00<00:00, 1228.19frame/s]
Saving 1_04_0_30fps_flip_flipcode-1.mp4: 100%|██████████| 30/30 [00:00<00:00, 1166.70frame/s]
Saving 1_04_0_30fps_flip_flipcode-0.mp4: 100%|██████████| 30/30 [00:00<00:00, 1189.87frame/s]
Saving 1_04_0_30fps_flip_flipcode--1.mp4: 100%|██████████| 30/30 [00:00<00:00, 1120.28frame/s]
Saving 1_04_0_30fps_grayscale.mp4: 100%|██████████| 30/30 [00:00<00:00, 1208.51frame/s]
Saving 1_04_0_30fps_rotate_angle-15.mp4: 100%|██████████| 30/30 [00:00<00:00, 1090.70frame/s]
Saving 1_04_0_30fps_rotate_angle--15.mp4: 100%|██████████| 30/30 [00:00<00:00, 1210.54frame/s]

{'cropped': '/home/mojtaba.kananisarche/Zh/temp/out/cropped/1_04_0_30fps_cropped.mp4',
 'gaussian_blur_kernelsize-3': '/home/mojtaba.kananisarche/Zh/temp/out/gaussian_blur_kernelsize-3/1_04_0_30fps_gaussian_blur_kernelsize-3.mp4',
 'gaussian_blur_kernelsize-5': '/home/mojtaba.kananisarche/Zh/temp/out/gaussian_blur_kernelsize-5/1_04_0_30fps_gaussian_blur_kernelsize-5.mp4',
 'brightness_alpha-1.2_beta-10': '/home/mojtaba.kananisarche/Zh/temp/out/brightness_alpha-1.2_beta-10/1_04_0_30fps_brightness_alpha-1.2_beta-10.mp4',
 'brightness_alpha-0.8_beta--10': '/home/mojtaba.kananisarche/Zh/temp/out/brightness_alpha-0.8_beta--10/1_04_0_30fps_brightness_alpha-0.8_beta--10.mp4',
 'contrast_alpha-1.5_beta-0': '/home/mojtaba.kananisarche/Zh/temp/out/contrast_alpha-1.5_beta-0/1_04_0_30fps_contrast_alpha-1.5_beta-0.mp4',
 'contrast_alpha-0.7_beta-0': '/home/mojtaba.kananisarche/Zh/temp/out/contrast_alpha-0.7_beta-0/1_04_0_30fps_contrast_alpha-0.7_beta-0.mp4',
 'flip_flipcode-1': '/home/mojtaba.kananisarche/Zh/temp/out/flip_flipcode-1/1_04_0_30fps_flip_flipcode-1.mp4',
 'flip_flipcode-0': '/home/mojtaba.kananisarche/Zh/temp/out/flip_flipcode-0/1_04_0_30fps_flip_flipcode-0.mp4',
 'flip_flipcode--1': '/home/mojtaba.kananisarche/Zh/temp/out/flip_flipcode--1/1_04_0_30fps_flip_flipcode--1.mp4',
 'grayscale': '/home/mojtaba.kananisarche/Zh/temp/out/grayscale/1_04_0_30fps_grayscale.mp4',
 'rotate_angle-15': '/home/mojtaba.kananisarche/Zh/temp/out/rotate_angle-15/1_04_0_30fps_rotate_angle-15.mp4',
 'rotate_angle--15': '/home/mojtaba.kananisarche/Zh/temp/out/rotate_angle--15/1_04_0_30fps_rotate_angle--15.mp4'}

In [1]:
import subprocess
import sys

# # List of required packages
# required_packages = [
#     'opencv-python',
#     'mediapipe',
#     'pandas',
#     'numpy',
#     'tqdm',
#     'scikit-learn',
#     'mord',
#     'tensorflow',
#     'matplotlib',
#     'tensorflow-addons',
#     'imbalanced-learn'
# ]

# # Function to install packages if not already installed
# def install_package(package):
#     subprocess.check_call([sys.executable, "-m", "pip", "install", package])

# # Check and install missing packages
# for package in required_packages:
#     try:
#         __import__(package)
#     except ImportError:
#         print(f"{package} not found, installing...")
#         install_package(package)

# Now, import the libraries

import os
import cv2
import mediapipe as mp
import pandas as pd
import numpy as np
from tqdm import tqdm
from multiprocessing import Pool
import logging
from concurrent.futures import ThreadPoolExecutor, ProcessPoolExecutor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from mord import LogisticAT  # Ordinal logistic regression
from sklearn.metrics import classification_report, confusion_matrix, mean_absolute_error, root_mean_squared_error
import tensorflow as tf
from tensorflow import keras
from keras import layers
import matplotlib.pyplot as plt
from keras import backend as K
from keras import losses
from keras.layers import Lambda
from sklearn.utils.class_weight import compute_class_weight, compute_sample_weight
from keras.preprocessing.sequence import pad_sequences
import random
import concurrent.futures
from tqdm import tqdm
from datetime import datetime
import json

2025-03-10 00:59:30.544042: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-03-10 00:59:33.066353: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2025-03-10 00:59:40.642650: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-03-10 00:59:40.642721: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-03-10 00:59:42.702394: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-03-10 00:59:45.884922: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2025-03-10 00:59:45.887581: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-03-10 01:00:29.509131: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

In [2]:
# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    handlers=[
        logging.FileHandler("process_video.log"),
        logging.StreamHandler()
    ]
)

In [3]:
# Function to set the random seed
def set_seed(seed=42):
    os.environ['PYTHONHASHSEED'] = str(seed)
    random.seed(seed)
    np.random.seed(seed)
    tf.random.set_seed(seed)
    tf.config.experimental.enable_op_determinism()

In [4]:
def replace_target(value, mapping):
    return mapping[str(value)]

In [5]:
def step(val, steps, outputs):
    for i in range(len(steps)-1):
        low = steps[i]
        high = steps[i+1]
        if val >= low and val <= high:
            return outputs[i]

In [6]:
def get_prediction(raw_pred):
    # Clip to ensure within range
    clipped = np.clip(raw_pred, 1, 9)
    # Round to nearest integer
    return np.round(clipped).astype(int)

In [8]:
def reshape_data_rnn(df, feature_columns=[], max_slices=30, sortby_column='slice_index', target_column='target'):
    X, y = [], []
    
    grouped = df.groupby('filename')
    
    for video, group in grouped:
        # Sort by slice_index to maintain temporal order
        group = group.sort_values(by=sortby_column)

        # Extract features
        slices = group[feature_columns].values.tolist()

        # Split into chunks of max_slices
        for i in range(0, len(slices), max_slices):
            chunk = slices[i:i + max_slices]
            X.append(chunk)
            y.append(group[target_column].iloc[0])  # Same label for all chunks from the same video

    # Pad sequences to the max_slices length
    X_padded = pad_sequences(X, maxlen=max_slices, padding='post', dtype='float32')

    # Convert labels to numpy array
    y = np.array(y)
    
    return X_padded, y

In [9]:
def ordinal_loss(y_true, y_pred):
    # Round the prediction to get integer values
    y_pred_rounded = tf.round(y_pred)
    # Clip to ensure values are between 1 and 9
    y_pred_clipped = tf.clip_by_value(y_pred_rounded, 1, 9)
    # Calculate MSE with the clipped values
    return tf.reduce_mean(tf.square(y_true - y_pred_clipped))

In [10]:
logging.info(f"Starting")
set_seed(42)

2025-03-10 01:02:44,262 - INFO - Starting

In [11]:
dataset_name = "Blendshapes_Summary_100_100_0.6_45_3.csv"
df = pd.read_csv(f"/home/mojtaba.kananisarche/Zh/UTA/Blendshapes/Summary/{dataset_name}", index_col=0)
print(df.shape)

df.head()

(32683, 282)

,slice_index,filename,start_frame,end_frame,_neutral_mean,browDownLeft_mean,browDownRight_mean,browInnerUp_mean,browOuterUpLeft_mean,browOuterUpRight_mean,...,blinks_median_duration,blinks_std_duration,blinks_min_duration,blinks_max_duration,naps_count,naps_mean_duration,naps_median_duration,naps_std_duration,naps_min_duration,naps_max_duration
0,0,2_21_10_30fps_blendshape.csv,0,99,0.0,0.0083,0.0047,0.1579,0.2362,0.2081,...,3.0,2.309401,3,7,0,0.0,0.0,0.0,0,0
1,1,2_21_10_30fps_blendshape.csv,100,199,0.0,0.0074,0.0031,0.1580,0.2405,0.2433,...,4.0,0.000000,4,4,0,0.0,0.0,0.0,0,0
2,2,2_21_10_30fps_blendshape.csv,200,299,0.0,0.0117,0.0083,0.1100,0.2051,0.1928,...,6.5,3.535534,4,9,0,0.0,0.0,0.0,0,0
3,3,2_21_10_30fps_blendshape.csv,300,399,0.0,0.0194,0.0098,0.0821,0.1609,0.1653,...,5.0,0.000000,5,5,0,0.0,0.0,0.0,0,0
4,4,2_21_10_30fps_blendshape.csv,400,499,0.0,0.0170,0.0092,0.0900,0.1756,0.1827,...,3.0,1.000000,2,4,0,0.0,0.0,0.0,0,0

In [12]:
mapping = {
    '10' : 8.5,
    '5' : 6.5,
    '0' : 2
}

df['fold'] = df['filename'].apply(lambda x: int(x.split('_')[0]))
df['subject_id'] = df['filename'].apply(lambda x: int(x.split('_')[1]))
df['target'] = df['filename'].apply(lambda x:mapping.get(x.split('_')[2]))
# df.drop('filename', axis=1, inplace=True)

df.head()

,slice_index,filename,start_frame,end_frame,_neutral_mean,browDownLeft_mean,browDownRight_mean,browInnerUp_mean,browOuterUpLeft_mean,browOuterUpRight_mean,...,blinks_max_duration,naps_count,naps_mean_duration,naps_median_duration,naps_std_duration,naps_min_duration,naps_max_duration,fold,subject_id,target
0,0,2_21_10_30fps_blendshape.csv,0,99,0.0,0.0083,0.0047,0.1579,0.2362,0.2081,...,7,0,0.0,0.0,0.0,0,0,2,21,8.5
1,1,2_21_10_30fps_blendshape.csv,100,199,0.0,0.0074,0.0031,0.1580,0.2405,0.2433,...,4,0,0.0,0.0,0.0,0,0,2,21,8.5
2,2,2_21_10_30fps_blendshape.csv,200,299,0.0,0.0117,0.0083,0.1100,0.2051,0.1928,...,9,0,0.0,0.0,0.0,0,0,2,21,8.5
3,3,2_21_10_30fps_blendshape.csv,300,399,0.0,0.0194,0.0098,0.0821,0.1609,0.1653,...,5,0,0.0,0.0,0.0,0,0,2,21,8.5
4,4,2_21_10_30fps_blendshape.csv,400,499,0.0,0.0170,0.0092,0.0900,0.1756,0.1827,...,4,0,0.0,0.0,0.0,0,0,2,21,8.5

In [60]:
def report(model, x, y_true, unique_classes):
    y_true = np.array(y_true)
    y_pred = np.array(model.predict(x, verbose=0)).flatten()
    results = {}
    for cls in unique_classes:
        idx = y_true == cls
        if np.all(idx == False):
            results[cls] = -1
            continue
        mae = root_mean_squared_error(y_true[idx], y_pred[idx])
        results[cls] = mae

    return y_pred, results

In [61]:
class NumpyEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, (np.integer)):
            return int(obj)
        elif isinstance(obj, (np.floating)):
            return round(float(obj), 1)
        elif isinstance(obj, (np.ndarray)):
            return [round(float(x), 1) if isinstance(x, (np.floating, float)) else x for x in obj.tolist()]
        return super(NumpyEncoder, self).default(obj)

In [62]:

class Model:
    def __init__(self, units, dropout_ratio, kernel_regularizer_l2, kernel_regularizer_l1, batch_size, num_classes, learning_rate, weight_decay, beta_1, beta_2, epsilon, epochs, patience, max_slices, dataset_name):
        self.units = units
        self.dropout_ratio = dropout_ratio
        self.kernel_regularizer_l2 = kernel_regularizer_l2
        self.kernel_regularizer_l1 = kernel_regularizer_l1
        self.batch_size = batch_size
        self.num_classes = num_classes
        self.learning_rate = learning_rate
        self.weight_decay = weight_decay
        self.beta_1 = beta_1
        self.beta_2 = beta_2
        self.epsilon = epsilon
        self.epochs = epochs
        self.patience = patience
        self.max_slices = max_slices
        self.dataset_name = dataset_name
        self.dataset_id = self.dataset_name.split("Blendshapes_Summary_")[1].split(".csv")[0]
        self.models = []
        self.histories = []
        self.reports = []
        
        
    def build_model(self, input_shape):
        model = keras.Sequential()
        model.add(layers.Input(shape=(input_shape[0], input_shape[1])))

        # Add LSTM layers
        for u in self.units[:-1]:
            model.add(layers.LSTM(u, activation='tanh', return_sequences=True, 
                                  kernel_regularizer=tf.keras.regularizers.l2(self.kernel_regularizer_l2)))
            model.add(layers.BatchNormalization())
            model.add(layers.Dropout(self.dropout_ratio))

        # Final LSTM layer without return_sequences
        model.add(layers.LSTM(self.units[-1], activation='tanh', 
                              kernel_regularizer=tf.keras.regularizers.l2(self.kernel_regularizer_l2)))
        model.add(layers.BatchNormalization())
        model.add(layers.Dropout(self.dropout_ratio))

        # Final output layer
        model.add(layers.Dense(1, activation='sigmoid'))  # Use sigmoid activation

        # Use a custom output layer to scale the output to 1-9
        model.add(layers.Lambda(lambda x: x * 8 + 1)) 

        model.compile(
            optimizer = keras.optimizers.AdamW(
                learning_rate=self.learning_rate,
                weight_decay=self.weight_decay,
                beta_1=self.beta_1,
                beta_2=self.beta_2,
                epsilon=self.epsilon
            ),
            loss='mse',
            metrics=['mae']
        )

        return model



    # First, define the train_single_fold function outside of the class
    def _train_single_fold(self, args):
        """Helper function for parallel processing in test_model.

        Args:
            args: Tuple containing (model_instance, test_idx, val_idx, data)

        Returns:
            Dictionary containing model, history, and reports
        """
        self, test_subject_idx, data = args
        local_results = {}

        subject_fold = data[data['subject_id']==test_subject_idx]['fold'].values[0]
        validation_subjects_idx = data[(data['subject_id']!=test_subject_idx) & (data['fold']==subject_fold)]['subject_id'].unique().tolist()
        logging.info(f"Starting Test {test_subject_idx} & Validation {validation_subjects_idx}")

        train = data[~data['subject_id'].isin(validation_subjects_idx + [test_subject_idx])]
        val   = data[data['subject_id'].isin(validation_subjects_idx)]
        test  = data[data['subject_id']==test_subject_idx]
        logging.info(f"train {train.shape} & val {val.shape} & test {test.shape}")

        # List of columns to exclude from scaling
        exclude_cols = ['slice_index', 'filename', 'start_frame', 'end_frame', 'target', 'fold', 'subject_id']
        feature_columns = data.columns.difference(exclude_cols)

        # Fit the scaler on the training data
        scaler = StandardScaler().fit(train[feature_columns])

        # Transform the training, validation, and test data
        train_scaled = scaler.transform(train[feature_columns])
        val_scaled   = scaler.transform(val[feature_columns]  )
        test_scaled  = scaler.transform(test[feature_columns] )

        # Convert scaled arrays back to DataFrames and add the excluded columns
        train_scaled_df = pd.DataFrame(train_scaled, columns=feature_columns, index=train.index)
        val_scaled_df   = pd.DataFrame(val_scaled,   columns=feature_columns, index=val.index  )
        test_scaled_df  = pd.DataFrame(test_scaled,  columns=feature_columns, index=test.index )

        # Concatenate the scaled features with the excluded columns
        train = pd.concat([train_scaled_df, train[exclude_cols]], axis=1)
        val   = pd.concat([val_scaled_df,   val[exclude_cols]],   axis=1)
        test  = pd.concat([test_scaled_df,  test[exclude_cols]],  axis=1)

        X_train, y_train = reshape_data_rnn(train, feature_columns, max_slices=self.max_slices, sortby_column='slice_index', target_column='target')
        X_val,   y_val   = reshape_data_rnn(val,   feature_columns, max_slices=self.max_slices, sortby_column='slice_index', target_column='target')
        X_test,  y_test  = reshape_data_rnn(test,  feature_columns, max_slices=self.max_slices, sortby_column='slice_index', target_column='target')

        sample_weight = compute_sample_weight(class_weight='balanced', y=y_train)

        model = self.build_model((X_train.shape[1], X_train.shape[2]))

        # Train the model
        history = model.fit(
            X_train,
            y_train,
            validation_data=(X_val, y_val),
            epochs=self.epochs,
            batch_size=self.batch_size,
            callbacks=[keras.callbacks.EarlyStopping(monitor='val_loss', patience=self.patience, restore_best_weights=True)],
            verbose=0,  # Reduced verbosity for parallel execution
            sample_weight=sample_weight
        )

        y_train_pred, train_report = report(model=model, x=X_train, y_true=y_train, unique_classes=[2, 6.5, 8.5])
        y_val_pred,   val_report   = report(model=model, x=X_val,   y_true=y_val,   unique_classes=[2, 6.5, 8.5])
        y_test_pred,  test_report  = report(model=model, x=X_test,  y_true=y_test,  unique_classes=[2, 6.5, 8.5])

        # Store results to return
        local_results = {
            'test': test_subject_idx,
            'val': validation_subjects_idx,
            'history': history.history,
            'train_report': train_report,
            'y_train': y_train,
            'y_train_pred': y_train_pred,
            'val_report': val_report,
            'y_val': y_val,
            'y_val_pred': y_val_pred,
            'test_report': test_report,
            'y_test': y_test,
            'y_test_pred': y_test_pred,
        }
        
        logging.info(f"epoch : {len(history.history['val_loss'])}")
        logging.info(f"Completed Test {test_subject_idx} & Validation {validation_subjects_idx}")
        logging.info('=======================================')

        return local_results
            

    def test_model(self, data):
        unique_subject_id = data['subject_id'].unique()

        logging.info(f"Found {len(unique_subject_id)} valid test-validation pairs.")

        # Prepare arguments for parallel processing
        args_list = [(self, i, data) for i in unique_subject_id]
        random.shuffle(args_list)

        output_folder_name = datetime.now().strftime("%Y-%m-%d|%H:%M:%S|RNN")
        output_parent_dir = "/home/mojtaba.kananisarche/Zh/UTA/Output/"
        output_folder_path = os.path.join(output_parent_dir, output_folder_name)
        os.makedirs(output_folder_path, exist_ok=True)

        with open(os.path.join(output_folder_path, 'results.json'), 'w') as file:
            json.dump({
                'general':{
                    'units':self.units,
                    'dropout_ratio':self.dropout_ratio,
                    'batch_size':self.batch_size,
                    'learning_rate':self.learning_rate,
                    'weight_decay':self.weight_decay,
                    'epochs':self.epochs,
                    'dataset_id':self.dataset_id,
                    'max_slices':self.max_slices
                }
            }, file)

        # Run training in parallel and process results as they come
        all_results = []

        # with concurrent.futures.ProcessPoolExecutor(max_workers=1) as executor:
        #     futures = [executor.submit(self._train_single_fold, args) for args in args_list]
        #     for future in tqdm(concurrent.futures.as_completed(futures), total=len(futures), desc="Training folds"):
        #         result = future.result()

        results = [self._train_single_fold(args) for args in args_list]
        for result in results:
            file_path = os.path.join(output_folder_path, f'{result["test"]}.json')
            with open(file_path, 'w') as file:
                json.dump(result, file, cls=NumpyEncoder, indent=4)
                logging.info(f"Saved results for Test subject {result['test']} to {file_path}")
                
                    
                # Process results
        for result in all_results:
            self.models.append(result['model'])
            self.histories.append(result['history'])
            self.reports.append({
                'test': result['test'],
                'val': result['val'],
                'train_report': result['train_report'],
                'val_report': result['val_report'],
                'test_report': result['test_report']
            })
        logging.info(f"Completed all {len(unique_subject_id)} test-validation pairs.")

In [63]:
m = Model(units = [1], 
        dropout_ratio = 0.3, 
        kernel_regularizer_l2 = 0, 
        kernel_regularizer_l1 = 0, 
        batch_size = 32, 
        num_classes = 3, 
        learning_rate = 1e-3, 
        weight_decay = 1e-4, 
        beta_1 = 0.9, 
        beta_2 = 0.999, 
        epsilon = 1e-7,
        epochs = 1, 
        patience = 100,
        max_slices=50,
        dataset_name = dataset_name)

m.test_model(df)

2025-03-10 01:27:06,136 - INFO - Found 60 valid test-validation pairs.
2025-03-10 01:27:06,173 - INFO - Starting Test 42 & Validation [39, 38, 37, 40, 43, 44, 45, 46, 47, 41, 48]
2025-03-10 01:27:06,198 - INFO - train (27222, 285) & val (5101, 285) & test (360, 285)
2025-03-10 01:27:10,450 - INFO - epoch : 1
2025-03-10 01:27:10,451 - INFO - Completed Test 42 & Validation [39, 38, 37, 40, 43, 44, 45, 46, 47, 41, 48]
2025-03-10 01:27:10,452 - INFO - =======================================
2025-03-10 01:27:10,457 - INFO - Saved results for Test subject 42 to /home/mojtaba.kananisarche/Zh/UTA/Output/2025-03-10|01:27:06|RNN/42.json
2025-03-10 01:27:10,459 - INFO - Completed all 1 test-validation pairs.